### ISSUE TITLE
`AudioParam.cancelAndHoldAtTime()` breaks in Chrome when using `standardized-audio-context`

### ISSUE THREAD

**Issue by satelllte** [chrisguttandin/standardized-audio-context#1002]
Hi 👋 

I've just built this quick [audioparam-visualization](https://github.com/satelllte/audioparam-visualization) demo and realized that Firefox lacks the support of `AudioParam` methods significantly, so I decided to try this ponyfill to see if it fixes the issue (it's not, but that's another topic). 

But finally I've noticed that `cancelAndHoldAtTime()` calls start breaking even in Chrome. 

---

- Demo with Native Web Audio API: https://audioparam-visualization.vercel.app
  - `cancelAndHoldAtTime()` works fine in Chrome

- Demo with `standardized-audio-context`: https://audioparam-visualization-git-std-audio-ctx-test-satelllte.vercel.app 
  - `cancelAndHoldAtTime()` started to break in Chrome, see console error for more details

- Source code diff: https://github.com/satelllte/audioparam-visualization/pull/13/files 
  - nothing special, simple replacement of native Web Audio API's classes to the ones from `standardized-audio-context`

**Comment by satelllte** [comment]
@chrisguttandin This is the error:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/20585619/230738019-652f8b7e-dae6-4c2b-ac86-d9eb55f1fed9.png">

So far I couldn't find why is this happening since I'm unfamiliar with the codebase

**Comment by chrisguttandin** [comment]
The error actually came from `automation-events` which is used internally. It wasn't properly handling if there was a ramp without any previous event. It should be fixed now.

**Comment by satelllte** [comment]
Thank you 🙏 
I'll try it soon

**Comment by satelllte** [comment]
@chrisguttandin `cancelAndHoldAtTime()` isn't breaking no more in Chrome, though I started to see some issues with these methods in Chrome:
- `linearRampToValueAtTime()`
- `exponentialRampToValueAtTime()`
- `cancelAndHoldAtTime()`

Just compare these versions (it's just easier to see the difference audio-visually than explain):
- Native Web Audio API: https://audioparam-visualization.vercel.app/
- With `standardized-audio-context@25.3.43`: https://audioparam-visualization-git-std-audio-ctx-test-satelllte.vercel.app/

**Comment by chrisguttandin** [comment]
Thanks a lot for following up on this. Turns out there is another browser bug which I wasn't aware of so far. I used the `defaultValue` to insert the implicit events. Unfortunately that's not implemented correctly in Chrome and Firefox.

I believe the latest changes (https://github.com/chrisguttandin/standardized-audio-context/commit/217e3a3fde153874806d06b6fe8e6d29a76a567f) released as v25.3.45 should finally fix it.

But as always please let me know if you encounter any further problems.

**Comment by satelllte** [comment]
Now it works! Thank you 🙏 
DEMO: https://audioparam-visualization-git-std-audio-ctx-test-satelllte.vercel.app
