### ISSUE TITLE
Question about missing `AudioParam` methods in Firefox

### ISSUE THREAD

**Issue by satelllte** [chrisguttandin/standardized-audio-context#1003]
Hi again 👋🏻 

In the previous issue I've logged https://github.com/chrisguttandin/standardized-audio-context/issues/1002 I mentioned that I decided to try this ponyfill to see if it adds the support for missing or not fully implemented `AudioParam` methods in Firefox and I see it doesn't.

So what I see is missing so far:

- `linearRampToValueAtTime()` doesn't work properly, it just behaves like `setValueAtTime()`
- `exponentialRampToValueAtTime()` doesn't work properly, it just behaves like `setValueAtTime()`
- `cancelAndHoldAtTime()` is not supported

---

Question: I'm just wondered is it possible to "re-implement" them in this library? Or is it out of scope & goal of it? 

I'm just thinking that:
- `linearRampToValueAtTime()` could be implemented via `setValueCurveAtTime()` potentially
- `exponentialRampToValueAtTime()` could be implemented via `setTargetAtTime()` potentially
- `cancelAndHoldAtTime()` maybe could be implemented also somehow using the combination of supported methods 😊

**Comment by satelllte** [comment]
This question is more general actually & relates not only to Firefox but any browser that lack the support of something ^

My current debugging focus was just on Firefox lately 👌🏻

**Comment by chrisguttandin** [comment]
Hi @satelllte, thanks for giving `standardized-audio-context` a try. I think `linearRampToValueAtTime()` and `exponentialRampToValueAtTime()` work not as expected in your project because they need a previous event to start from. Both events only define the end value and assume there is a previous value in the timeline.

I think this is actually a bug in Chrome. It seems to insert an implicit `setValueAtTime()` event as the starting point. I think `standardized-audio-context` should prevent this. This is for example the relevant part from the spec for `linearRampToValueAtTime()`.

> If there is no event preceding this event, the linear ramp behaves as if [setValueAtTime(value, currentTime)](https://webaudio.github.io/web-audio-api/#dom-audioparam-setvalueattime) were called where value is the current value of the attribute and currentTime is the context [currentTime](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-currenttime) at the time [linearRampToValueAtTime()](https://webaudio.github.io/web-audio-api/#dom-audioparam-linearramptovalueattime) is called.

**Comment by chrisguttandin** [comment]
Sorry for the confusion. It looks like I didn't really read the text that I just pasted a few hours ago. Reading it again, I think Chrome is behaving correctly and Firefox should do the same. I'll try to come up with a fix.

**Comment by satelllte** [comment]
> Sorry for the confusion. It looks like I didn't really read the text that I just pasted a few hours ago. Reading it again, I think Chrome is behaving correctly and Firefox should do the same. I'll try to come up with a fix.

Thank you for the answer! This issue primary focus is on un-implemented things in Firefox, but I think #1002 is just more critical bug because `cancelAndHoldAtTime()` in Chrome starts breaking, so would be glad if you could take a look at it first 🙏

**Comment by chrisguttandin** [comment]
I think both issues are somehow related to each other. I've made some changes to make sure there is an implicitly added `setValueAtTime()` event. It should make all browsers behave correctly.

It should also fix #1002 as there will no longer be a situation in which there is a ramp without a previous event.

I just published v25.3.42 which contains the fix. Please let me know if the issue still persists.

**Comment by satelllte** [comment]
Thank you 🙏 
I'll try it soon
