### ISSUE TITLE
"InvalidStateError" in Safari Version 17.0 (Macbook M1 Pro)

### ISSUE THREAD

**Issue by rutvik106** [chrisguttandin/standardized-audio-context#1007]
Hi, I am trying to play streaming audio coming from my websocket connection and I am getting error in Safari. The audio plays a little bit and then it breaks giving an error. It works perfect in Chrome.

Here is my code Vue JS Code

```
<script>

import {AudioContext, decodeAudioData} from 'standardized-audio-context'

export default {

    data() {
        return {

            socket: null,
            connected: false,
            audioQueue: [],
            isPlaying: false,

        }
    },

    methods: {

        init() {

            let vm = this

            const audioContext = new AudioContext()

            vm.socket = new WebSocket('wss://audio-streaming-api-url')
            vm.socket.binaryType = 'arraybuffer'

            vm.socket.addEventListener("open", async () => {

                vm.connected = true
                console.log("WebSocket is open.")

            })

            vm.socket.addEventListener("message", (event) => {

                this.audioQueue.push(event.data)

                if (!this.isPlaying) {
                    this.playNextChunk(audioContext)
                }

            })

            vm.socket.addEventListener("close", () => {
                vm.connected = false
                console.log("WebSocket is closed.")
            })

        },

        async playNextChunk(audioContext) {

            if (this.audioQueue.length === 0) {
                this.isPlaying = false
                return
            }

            this.isPlaying = true
            const audioData = this.audioQueue.shift()

            try {
                const audioBuffer = await decodeAudioData(audioContext, audioData)
                console.log(audioData)
                const source = audioContext.createBufferSource()
                source.buffer = audioBuffer
                source.connect(audioContext.destination)
                source.onended = this.playNextChunk
                source.start()
            } catch (error) {
                this.isPlaying = false
                this.socket.close()
                console.error('Error decoding audio data', error)
            }
        },

    },

    mounted() {
        this.init()
    }

}

</script>
```

**Comment by chrisguttandin** [comment]
Hi @rutvik106, thanks for reporting this.

Is the error thrown by `decodeAudioData()` or anywhere else? I think according to the spec the only reason why `decodeAudioData()` could throw an error is when the document is not fully active which I guess is not the case.

https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata

Which file format are you using? Maybe Safari is not capable of decoding it in chunks?

**Comment by rutvik106** [comment]
<img width="571" alt="Screenshot 2023-10-24 at 2 02 12 PM" src="https://github.com/chrisguttandin/standardized-audio-context/assets/6727175/98ad5c27-46f2-41f1-b6f1-aba3dd974d96">
It is throwing the error here.

I don't know what do you mean by "when the document is not fully active" does that mean that there should be some interaction on the page via gesture or button click? I am already pressing a button to fire this process.

I don't know which format I am receiving. I have a Python server which is sending the text converted into speech using Elevenlabs.io and they have this code example https://docs.elevenlabs.io/api-reference/text-to-speech-websockets#other-examples which I have implemented on my backend. chunk = base64.b64decode(data["audio"]) I am sending this chunk data back to client using websocket.

**Comment by chrisguttandin** [comment]
Thanks for providing further details.

The documentation on evenlabs.io says that the default audio format is mp3. You can check this by logging the first few bytes of each chunk.

If you add this to your `'message'` handler, what will it log?

```js
const textDecoder = new TextDecoder();
textDecoder.decode(event.data.slice(0, 10)); 
```

**Comment by rutvik106** [comment]
In console log it shows following

<img width="612" alt="Screenshot 2023-10-24 at 8 21 38 PM" src="https://github.com/chrisguttandin/standardized-audio-context/assets/6727175/bf70f626-992c-4f92-ae0c-a9b54d0aa31b">


```
vm.socket.addEventListener("message", (event) => {

               const textDecoder = new TextDecoder();
               console.log(textDecoder.decode(event.data.slice(0, 10)))

});
```

**Comment by chrisguttandin** [comment]
This does indeed look like sliced MP3s. Maybe you can get Safari to decode them by combining a few of those chunks before calling `decodeAudioData()`. It looks like it's not a giant MP3 but a number of smaller MP3s split across a few chunks.

The brute-force way to handle this could be to run `decodeAudioData()` on each new chunk with a `try/catch`. If it fails you append it to the previous one that worked and run `decodeAudioData()` again.

A project which slices an MP3 in a way that produces new valid files is [phonograph](https://github.com/Rich-Harris/phonograph). Maybe that could serve as a source of inspiration.

Since there is nothing that could be done in `standardized-audio-context` I'm going to close this issue. I think when interpreting the spec very strictly, Chrome is actually wrong because it decodes incomplete files which it should reject.
