### ISSUE TITLE
"EncodingError: Decoding failed" on IOS only when decoding mp3 chunks

### ISSUE THREAD

**Issue by royibernthal** [chrisguttandin/standardized-audio-context#1013]
I'm streaming mp3 chunks that are generated by a 3rd party to the browser via socket io.

The audio format is mp3 with 44.1kHz sample rate at 192kbps.

I'm starting to play the first chunk as soon as it arrives - it's a bit bigger than the rest and it's a valid mp3 that can be decoded on it's own. Subsequent chunks aren't valid mp3 files that can be decoded by decodeAudioData() in the browser, i.e. they don't begin and end exactly at the internal chunk boundaries of mp3.

Arbitrarily concatenating on the server the chunks that are generated by the 3rd party without paying attention to mp3's internal chunk boundaries, and as a result streaming bigger chunks (e.g. groups of 50 small chunks), seems to be working when playing the audio on Windows, but not on IOS.  I imagine the internal implementation of decodeAudioData() is different.

How would you go about turning the received mp3 chunks into valid ones that can be decoded on IOS? Or how would you otherwise approach this? The goal is to stream to the browser in real time audio that's generated by AI.

The following StackOverflow thread is not mine, but I believe the answer there touches the issue:
https://stackoverflow.com/questions/66450267/webaudioapi-decodeaudiodata-giving-null-error-on-ios-14-safari

**Comment by chrisguttandin** [comment]
I think this is related to https://stackoverflow.com/questions/78691781/audioworkletprocessor-playing-streamed-audio-sounds-scrambled. I therefore close this issue here. Please feel free to re-open it in case there is anything that needs to be fixed in standardized-audio-context.
