### ISSUE TITLE
decodeAudioData error when decoding PCM

### ISSUE THREAD

**Issue by royibernthal** [chrisguttandin/standardized-audio-context#1014]
I can't use decodeAudioData()  to decode PCM - both chunks and full files. I'm getting the following error:

DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

**Comment by chrisguttandin** [comment]
Unfortunately there is no way to make this work. The spec says `decodeAudioData()` is meant to decode "audio file data".

https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata

All it gets is an `ArrayBuffer` and expects that to contain a full file. If it only gets raw PCM data it has no way to know how to decode it.

But you could prepend a WAV header to make it work.
