### ISSUE TITLE
doubt regarding weather it can be used to modify the webkitspeech

### ISSUE THREAD

**Issue by pvscreations** [chrisguttandin/standardized-audio-context#1015]
In webkitspeech (speech to text) , webkitspeech automatically switches on the microphone and switches off,
now is there any possiblity that it can be used to modify the stream that is automatically taken by webkitspeech, so that i can add some noise or whatever in that audio stream....

**Comment by chrisguttandin** [comment]
Unfortunately there is no way to connect the Web Speech API with the Web Audio API or any other audio API in the browser, at least for now. There are a few issues (https://github.com/WICG/speech-api/issues/66, https://github.com/WICG/speech-api/issues/69, https://github.com/WICG/speech-api/issues/70) on the Web Speech API spec which ask for this feature. Hopefully it will be possible at some point in the future.
