### ISSUE TITLE
npm install error - issue with angular2 dpendency

### ISSUE THREAD

**Issue by bencpeters** [chrisguttandin/standardized-audio-context#15]
There seems to be an issue installing `v 0.5.4` right now - I'm getting problems resolving the `angular2` dependency:

```
npm ERR! peerinvalid The package zone.js does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.3 wants zone.js@0.5.11

npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "standardized-audio-context"
npm ERR! cwd /home/ubuntu/test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/test/npm-debug.log
npm ERR! not ok code 0
```

I see the `package.json` specifies `beta.1`, maybe `angular2@2.0.0-beta.3` updated its dependency on `zone.js` to conflict with the one that is defined by this package?

**Comment by chrisguttandin** [comment]
Many thanks for pointing that out. You are right, the dependencies were broken. I fixed it now. Please feel free to reopen this issue if the problem still persists on your end.
