### ISSUE TITLE
createMediaStreamDestination

### ISSUE THREAD

**Issue by liberatomota-itcenter** [chrisguttandin/standardized-audio-context#283]
Hello,
Can you implement the createMediaStreamDestination method?
I think this feature request falls in the "desperately need" category you talk in the readme..

Thanks,
Liberato Mota

**Comment by chrisguttandin** [comment]
Hi @liberatomota-itcenter,

unfortunately `createMediaStreamDestination()` is not available in all supported browsers. It is for example missing in Edge: https://github.com/chrisguttandin/standardized-audio-context/blob/1ad8514ef28ed6448b832d08c309563108ce56aa/test/expectation/edge/audio-context-constructor.js#L430

I don't know of a way to polyfill it, do you have any idea how that could be done?

Another option would be to change the return value of `isSupported()`. Currently the returned promise is either true or false. That means implementing the `createMediaStreamDestination()` method would make that promise resolve to false in Edge. Maybe the value could be changed from a primitive boolean to something more complex. But I don't really know what that should be.

Any ideas?

**Comment by liberatomota-itcenter** [comment]
Hello Chris,

Unfortunately I have no idea how this could be done either, but I don't think changing the `isSupported()` is necessary. 
The target browser where i'm having problems is web-kit, not Edge, and it's running in a webview inside the cordova app in iOS... tricky use case.

I will be tracking your package to see if in the future you are able o add this feature to your code :)

Thank you for the the reply and for the work you have put in creating the package
