### ISSUE TITLE
StereoPanner

### ISSUE THREAD

**Issue by KGRozanski** [chrisguttandin/standardized-audio-context#376]
Hi, I desperately need implementation of createStereoPanner(). I need to render my app server side and without your standardized-audio-context package CLI throws reference error of AudioContext. I could help to write it, but I need to know how ;(

**Comment by chrisguttandin** [comment]
Hi @KGRozanski, thanks for filing this issue. The StereoPanner is indeed missing and I'm happy to implement it. However I can't do it right now as I need to focus on paid projects for a while and my time for open source projects is currently limited.

Maybe there are other workarounds which could fix your issue in the meantime. Can you tell me a bit more about your use case? Which CLI are you referring to, for example.

I would of course also welcome a pull request which implements the StereoPanner. But be warned there needs to be a bit of code written. :-) Every AudioNode should have a set of tests which makes sure it works in all supported browsers (Chrome, Edge, Firefox, Opera & Safari). Here are those [tests for the GainNode](https://github.com/chrisguttandin/standardized-audio-context/blob/master/test/unit/audio-nodes/gain-node.js). Whenever there is something which needs to be patched I add an expectation test which does check if that browser bug really exists. This makes sure that this package only patches things which are still missing and doesn't end up patching stuff which are available in every browser anyway. Let me know if you want to do it, I'm happy to help.
