### ISSUE TITLE
es5 version not compiled correctly?

### ISSUE THREAD

**Issue by charlieroberts** [chrisguttandin/standardized-audio-context#399]
Hello,

When I try to use the es5 version (bundle.js) of SAC from npm I get a couple of errors. First is "line 104: _typeof does not exist". If I replaced that to just use regular `typeof`, then I get "sac.js:1448 Uncaught TypeError: _createClass is not a function".

Is using the es5 build from npm the simplest method of incorporating SAC into a html page (I'd like to avoid build systems for this particular project)? It would be great if, for example, SAC could instead be loaded of a CDN... thanks!

**Comment by chrisguttandin** [comment]
Hi Charlie,

the name of that file is somewhat misleading. It still needs to be bundled with webpack or something similar and is not self contained.

But luckily https://jspm.io/ allows npm packages to be bundled on the fly. I tried to put together a little example but unfortunately there is a bug in the build process which causes quotes to be escaped wrongly right now. I need to fix that first.

**Comment by chrisguttandin** [comment]
The following snippet works now as expected.

```html
<!DOCTYPE HTML>
<html lang="en">
    <body>
        <script type="module">
            import sac from 'https://dev.jspm.io/npm:standardized-audio-context';

            const audioContext = new sac.AudioContext();
            const oscillatorNode = new sac.OscillatorNode(audioContext);

            oscillatorNode.connect(audioContext.destination);

            oscillatorNode.start();
        </script>
    </body>
</html>
```

Unfortunately named exports do not work because https://jspm.io/ is using the ES5 bundle. Let me know if you run into any problems.

**Comment by charlieroberts** [comment]
Thank you!!! The AudioWorkletNode works great for me with simple examples, but for some reason my rather large complex module (thousands of lines of code) fails to load :( I'll let you know if I find out why, but I'm fairly certain this isn't a problem in `standardized-audio-context`, so I'm closing this.
