### ISSUE TITLE
Supported Browsers? 

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#443]
You mention that you test across various browsers and versions. could you publish which browsers/versions you are testing on?

**Comment by chrisguttandin** [comment]
Yes, sure. I also added a paragraph to the readme which explains the reasoning behind adding and removing polyfills to this package.

https://github.com/chrisguttandin/standardized-audio-context#browser-support

Please let me know if you think it doesn't make sense.

**Comment by tambien** [comment]
thanks for clarifying that! i think it'd be great to run the tests on and support the last two versions of the supported browsers. For example would be awesome to support Safari >=10. That way when safari does implement the full spec, previous versions are still supported for a while during the transition period. Though i do totally understand not wanting to add a ton of bloat and have to support outdated browsers forever (a la jQuery). Supporting the previous two versions of a browser is what [autoprefixer](https://autoprefixer.github.io/) does by default.
