### ISSUE TITLE
WaveShaperNode outputs incorrect values in Safari

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#445]
Not sure if the intention of this library is to normalize the functionality as well as the interface of Web Audio across implementations, but there a known issue with the WaveShaperNode in Safari that i'll point out in case you want to include the fix somehow:

Try running this code:
```javascript
import {OfflineAudioContext} from 'standardized-audio-context'

const context = new OfflineAudioContext(1, 441, 44100)

const waveshaper = context.createWaveShaper()
waveshaper.curve = Float32Array.from([0, 0.25, 0.5, 0.75, 1])

const signal = context.createConstantSource()
signal.offset.value = 0
signal.start(0)
signal.connect(waveshaper).connect(context.destination)

context.startRendering().then(buffer => {
	console.log(buffer.getChannelData(0)[0])
})
```

You'll see in Chrome and Firefox, the output is `0.5`, while in Safari the output is `0.625`. 

I've found that a simple fix to this issue is to increase the curve array length in Safari and repeat the first value. Something like this: 

```javascript
function setCurve(curve){
  var array = new Float32Array(curve.length+1);
  array.set(curve, 1);
  array[0] = curve[0];
  _internalNode.curve = array;
}
```

One issue is that this is a hard thing to test for without using the OfflineAudioContext like i did above, so the only way to know when to add the polyfill is by testing the userAgent which is often not the best practice.

**Comment by chrisguttandin** [comment]
Wow, thanks a lot @tambien.

It's definitely the goal to provide not only an API which has the same interface but also works consistently across all browsers.

Is that the bug which you are trying to fix here? https://github.com/Tonejs/Tone.js/blob/dev/Tone/shim/WaveShaperNode.js

**Comment by tambien** [comment]
yeah exactly! hoping you can also include that fix so i can eventually move to your AudioContext wrapper instead

**Comment by chrisguttandin** [comment]
Unfortunately adding a value at the beginning only fixes the issue with the center value. I looked up the source code and it seems like the whole scaling is done with a wrong offset in WebKit.

https://github.com/WebKit/webkit/blob/master/Source/WebCore/Modules/webaudio/WaveShaperDSPKernel.cpp#L106

Blink has that fixed:

https://chromium.googlesource.com/chromium/blink/+/master/Source/modules/webaudio/WaveShaperDSPKernel.cpp#104

But maybe that can be fixed by chaining two WaveShapers.

**Comment by tambien** [comment]
oh dang. i wonder if there's some way to make the behavior comparable.

**Comment by tambien** [comment]
I've been playing around with this and i've had some luck with rescaling the curve array to be much larger. A minimum curve length of something like 4096 seems ok. the values aren't the same between chrome and safari since i'm not sure there's a way to get around the different calculations which they're using, but at least the difference between the output values is fairly negligible when the array is that size. 

The scaling/resampling calculation which i'm using is basically the same as the interpolation algorithm in blink's WaveShaperDSPKernel.

**Comment by chrisguttandin** [comment]
I achieved some pretty good results by using two WaveShapers. Both are only operating on negative values. It works 100% correct for curves which basically resample a line. But it does of course have resampling issues for curves with other shapes. I will push it in a minute.

**Comment by chrisguttandin** [comment]
Hi @tambien, I'm sorry I initially planned to release a patch version, but now I have a problem with the tests running on Travis. I have to fix this first.

**Comment by chrisguttandin** [comment]
Version 17.5.6 finally includes the changes.

As always, please let me know if you encounter any bugs or problems.
