### ISSUE TITLE
Signal connected to playbackRate is not applied in Safari

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#479]
[This is a known issue in Safari](https://bugs.webkit.org/show_bug.cgi?id=127674), but hasn't been addressed for a few years. I'm wonder if this lib can also standardize the behavior of a signal connected to the playbackRate AudioParam in Safari. 

If you listen to [this pen](https://codepen.io/anon/pen/WPqmRa?editors=0011#0) in Safari and Chrome, you'll hear that the outcome is really different. The connected signal is not being applied to the AudioParam. 

Also, feel free to close this issue if this is outside the scope of the library or would add too much overhead or bloat to the code. It's an annoying issue that i've come across a few times, but i understand if the answer is that i've gotta work around it or wait until Safari has a new Web Audio release.

**Comment by chrisguttandin** [comment]
Hi @tambien,

thanks for providing this test case. And thanks for making me aware of that bug in the first place. I did not know it before.

I did at least add an expectation test for now to monitor the behavior in Safari. https://github.com/chrisguttandin/standardized-audio-context/commit/ff6f54885358aa89a4dd267f92bf7d9a1c5a3db3

Unfortunately I have no idea how this could be fixed. Do you have a clever workaround that you normally use?

**Comment by chrisguttandin** [comment]
Hi @tambien,

I found a solution that would allow to connect a signal to the `playbackRate` AudioParam in Safari. It would even be possible to extend it to support the `detune` AudioParam with the same workaround. However it does of course also have a drawback. It would introduce some additional delay as it uses a ScriptProcessorNode.

This is how the graph would look like:

```txt
┌──────────────────┐ ┌──────┐
│ConstantSourceNode│─│offset│ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
└──────────────────┘ └──────┘
         │                                                │
┌───────────────────┐       ┌─────────────────────┐ ┌────────────┐
│ScriptProcessorNode│       │AudioBufferSourceNode│─│playbackRate│
└───────────────────┘       └─────────────────────┘ └────────────┘
```

The AudioBufferSourceNode would be patched to start and stop the ConstantSourceNode when itself gets started and stopped. Inside the `onaudioprocess` callback of the ScriptProcessorNode the value of the ConstantSourceNode would be read at k-rate. Those values would be scheduled with `setValueAtTime()` on the original  `playbackRate` AudioParam. Luckily the `playbackRate` AudioParam is only allowed to be k-rate which allows to call `setValueAtTime()` at max every 128 samples. The `offset` AudioParam of the ConstantSourceNode would be exported as fake `playbackRate` AudioParam.

What do you think? Do you think this solution would be worth the tradeoff?

**Comment by chrisguttandin** [comment]
I decided to not add a fix for this for now. It will introduce a delay whenever an AudioBufferSourceNode is used even though nothing is connected to the playbackRate AudioParam. I couldn't find a way to avoid that.

Maybe this is something that could be solved by a module which works on top of standardized-audio-context and provides a `ConnectableAudioBufferSourceNode` or something similar.

In error will be thrown now in Safari if something gets connected to the playbackRate AudioParam. I think this better than failing silently.

**Comment by tambien** [comment]
@chrisguttandin makes sense! for such a low-level component, i agree that it wouldn't be good to add latency, or add extra code that might degrade performance. 

thanks for looking into that

**Comment by tambien** [comment]
This NotSupportedError which is thrown is causing some problems for me. It's also not technically the connection which is not supported (which is when the error is thrown), but the behavior which is expected of that connection which is the issue. 

I think failing silently is a better solution for this until Safari fixes the underlying problem. Might just be worth noting this as a 'cant fix' in the docs somewhere so if people come across this issue, they know what is causing it instead of throwing an error here.

**Comment by chrisguttandin** [comment]
Yes, you're right connecting something to the AudioParam is possible in Safari. But I'm not sure why you want to connect something if it doesn't have an effect. Isn't that a very confusing behavior? Can you please tell me a bit more about the problems that this is causing?

**Comment by tambien** [comment]
i've wrapped some AudioParams in the `Tone.Param` class which uses a GainNode as the input to the node and connects the GainNode to the AudiopParam. I add the GainNode as the initial input so that the internal AudioParam can be swapped out later if needed. This method fails in Safari with AudioBufferSourceNodes because i can't use a GainNode as the input node even when i'm not trying to control the internal signal with a connected node.

**Comment by chrisguttandin** [comment]
I'm not sure if I fully understood the use case. But I created a pull request which would probably fix the problem by catching the errors. It's just a suggestion though. Feel free to close it or to modify it as you like.

https://github.com/Tonejs/Tone.js/pull/548
