### ISSUE TITLE
Sample Rate bug in Safari

### ISSUE THREAD

**Issue by nchase** [chrisguttandin/standardized-audio-context#489]
I have noticed a sample rate bug in Safari. The bug is pretty well described in a few places (e.g. https://github.com/Tonejs/Tone.js/issues/134)

The [ios-safe-audio-context]( https://www.npmjs.com/package/ios-safe-audio-context) library fixes this bug, but it is over three years old and doesn't do any of the cool standardization stuff that this library does. 

Has anyone ever talked about moving that code into this library?

**Comment by chrisguttandin** [comment]
Hi @nchase, thanks for reporting this. I wasn't aware of that bug so far. I would be happy to add a fix for this problem to this library as well.

However I'm not sure if I understood how this can be tested and fixed. Do you know how the ios-safe-audio-context works? I noticed that it compares the sampleRate to a `desiredSampleRate` which is 44100 Hz by default. I wonder how one knows the desired sampleRate of a device? I don't know of anything (despite the AudioContext) which lets you know the sampleRate of the audio output device.

Furthermore I found a [bug filed on Webkit](https://bugs.webkit.org/show_bug.cgi?id=154538) which describes that the issue also occurs when the AudioContext is already running and after some time any other media with a different sampleRate starts to play. From looking at the code of ios-safe-audio-context I don't understand how the fix for that scenario works.

Can you maybe elaborate a bit on your specific use case?

**Comment by nchase** [comment]
Wow thanks for getting back to me @chrisguttandin  👋 A few things:

1. Actually, I don't understand how `ios-safe-audio-context` works or why it fixes the issue. And after testing, it doesn't seem to entirely fix the issue, but the sample rate is noticeably better (though not as good as in other browsers like Chrome or Firefox). I _think_ this issue is the same as what is described in the Webkit bug that you linked.
2. My use case is pretty simple (or so I think): I am creating a handful of `audioNode`s associated to `<audio>` elements on the page, via the audio context's `createMediaElementSource`. I connect those nodes to an `analyserNode` that I'm using for some WebGL visualization (I hope this isn't actually related to the bug that I'm seeing). I also connect the audio nodes to the context's `destination`.

Here's a demo that shows the behavior (if you play it in Safari you might notice the sample rate issues, in Chrome/Firefox the audio will sound clear): https://nchase.github.io/audio-next/

Here's the code that finds the `<audio>` elements, creates audio nodes, and connects them to analyser and destination: https://github.com/nchase/audio-next/blob/master/AudioContextContainer.js

**Comment by chrisguttandin** [comment]
Thanks for the link to your project. I tested it on my iPad and it worked very well. I didn't notice any glitches at all.

When I execute `console.log((new webkitAudioContext()).sampleRate);` in the console of Safari on the iPad it says 44.1kHz. I noticed that all the MP3s in your project have a sampleRate of 44.1kHz as well.

Therefore I replaced one of them with a different file which has a sampleRate of 48kHz. And once I did that I could hear very noticeable sampling problems.

I wonder what the sampleRate of your iOS device is. Is it 44.1kHz as well or is it 48kHz?

I also placed some breakpoints inside the code of the ios-safe-audio-context package. It never did anything in my case as the sampleRate was always 44.1kHz.

**Comment by nchase** [comment]
On my iPhone, the sampleRate for the same invocation is 48kHz.

**Comment by chrisguttandin** [comment]
Up to now it's only possible in Firefox to explicitly set the sampleRate of an AudioContext. So the following will work in Firefox.

```js
(new AudioContext({ sampleRate: 22050 })).sampleRate === 22050 
```

All other browsers pick the sampleRate that they think is best for the audio output device. There is no way to know that sampleRate in advance. It's 44100 on my computer and 48000 on my phone, for example.

I would, of course, love to add a fix for this to standardized-audio-context. But I'm afraid, that there is not much I can do about it.

If you have the time, could you maybe try to encode all your music files with a sampleRate of 48 kHz to see if this solves the issue with the iPhone?

**Comment by nchase** [comment]
that seems reasonable; given everything that we know, I expect that it will work. maybe I'll try it.

If I went further down this path, I could maintain two sets of files for the two different known sampleRates (I could check the sampleRate of a newly-instantiated AudioContext when I initialize my app, and load the appropriate files depending on the rate). I don't really want to do that, but I do want cross-platform support, so maybe I'll do that while I investigate more and try to lobby to get this resolved in WebKit, if it's reasonable to fix.

thanks for engaging, I'll re-open this if I find that there's something addressable that could reasonably done in the library.

**Comment by chrisguttandin** [comment]
Hi @nchase, can you please let me know if it actually works with files of a different sampleRate? I'm curious. :-)

And yes please feel free to reopen this issue if you have an idea how this could be fixed inside standardized-audio-context.

**Comment by nchase** [comment]
So an FYI: this totally worked with files of a different sampleRate (48000).

Not yet sure how this can be fixed, but I wanted to share something else strange that I observed: if I restart playback on the track, sometimes the audio is fine, despite the fact that the `audioContext` reports the wrong sampleRate. Safari definitely has some quirks here.

**Comment by chrisguttandin** [comment]
Hi @nchase, thanks for reporting back. That's really interesting.

Just to make sure I understood that correctly. Safari sometimes changes the sampleRate of a running AudioContext. Or in other words, it pretends to change the sampleRate by returning something different when calling `audioContext.sampleRate` as it did before. Is that correct?

**Comment by nchase** [comment]
It's even slightly stranger than that:

Here, `audioContext.sampleRate` is consistently _reporting_ `48000`. When I a load 41000Hz audio file, the sampleRate sounds like it jumps between 41000 and 48000Hz randomly when I pause and resume playback.

If I load a 48000Hz audio file in the same browser, there's no issue – it just sounds correct (and the `audioContext.sampleRate` still reports `48000`).

**Comment by nchase** [comment]
I still don't know much more about this, but here's a cool demo that someone created to illustrate it (you'll eventually notice a dramatic difference on your iOS device): https://jsfiddle.net/st___h/36w7vxn2/27/show

Their description of the issue: https://stackoverflow.com/questions/54982847/crackles-and-noises-when-playing-ios-web-audio-with-simple-graph/57366965

The author of those posts also posted here: https://forums.developer.apple.com/thread/114772

**Comment by chrisguttandin** [comment]
Thanks for the update.

Unfortunately I still think there is nothing we can do inside standardized-audio-context to fix this. But who knows maybe someone comes up with a crazy hack at some point which causes Safari to behave correctly. :-)
