### ISSUE TITLE
Fake AudioWorkletNode with 0 inputs throws errors on creation

### ISSUE THREAD

**Issue by PatrickStephansen** [chrisguttandin/standardized-audio-context#493]
When creating a new AudioWorkletNode intended to be a sound source, ie. with 0 inputs, processing crashes repeatedly as soon as the node is created in browsers other than Chrome. The error message is as follows:
```
TypeError: gainNodes[0] is undefined        native-audio-worklet-node-faker-factory.js:196
TypeError: undefined has no properties      native-audio-worklet-node-faker-factory.js:196
    dispatchEvent native-audio-worklet-node-faker-factory.js:196 
    onaudioprocess native-audio-worklet-node-faker-factory.js:255 
```
This can be worked around by declaring the node to have 1 input and just not using it in the `process` method.

I'll link a repo with minimal reproduction soon.

**Comment by chrisguttandin** [comment]
Hi @PatrickStephansen, thanks for reporting this bug. I guess I already know where the problem is. You don't have to create a reproducible test case.

**Comment by chrisguttandin** [comment]
Version [v19.0.3](https://www.npmjs.com/package/standardized-audio-context/v/19.0.3) is now published on npm.

Please let me know if you discover any further issues.

**Comment by PatrickStephansen** [comment]
Thanks. That was impressively quick.
