### ISSUE TITLE
When typescript targets ES6 module, the standardized-audio-context no longer works on Edge

### ISSUE THREAD

**Issue by 1jeffchristensen** [chrisguttandin/standardized-audio-context#513]
When using the npm package, in the file:
"/node_modules/standardized-audio-context/build/es2018/factories/analyser-node-constructor.js" the spread operator is used in an object literal which, as of Apr 2019, is not a feature of Edge. 

Perhaps this is just a npm package issue, and not a code issue here in the Git repo, or perhaps the repo here needs to be updated to also include an es2016 build output? Please advise!

**Comment by chrisguttandin** [comment]
Hi @1jeffchristensen,

a while ago I provided a number of different bundles but at some point I decided not to do it anymore. There are just too many options to cover all and there is no real standard to make them available through the package.json file.

Right now there is still the es5 bundle and then there is the es2018 code which represents the latest (well, actually it's 2019 now :-)) version of JavaScript. My idea was that any user can transpile that down to whatever version or feature combination is needed. I wanted to avoid choosing an arbitrary target version myself as it will surely be not enough for some users and far more than necessary for others.

I guess you are using webpack (or something similar) to bundle your JavaScript. In that case I would recommend to bring Babel into the mix and transpile the JavaScript to the version which best fits your use case.

I hope this all makes sense to you.

**Comment by 1jeffchristensen** [comment]
Look, what I am trying to tell you is that you say that you support Edge. But anybody who brings in your package finds that Edge in fact does not work. I understand that I bring "another" transpiler into the mix, that your es2018 package would work for Edge. Although I completely disagree with that premise. You have 2 packages: a super old ES5 one, and the latest ES package. I am recommending that you include one such as ES6 that fulfills your goal of supporting all browsers with a simple NPM package. Then you could also remove support for ES5 since that is unnecessary.

You also do not need to build up a straw man claiming that "there are too many options" to cover so you are just going to leave it up to users to compile it on their own. That is a poor argument for not wanting to include an ES6 package.

**Comment by chrisguttandin** [comment]
Hi @1jeffchristensen,

I can understand your frustration. The paragraph about browser support was not clear enough. I fixed that now. Browser support in the context of this package only means that the features are implemented. It doesn't cover the syntax as well. Thanks for making me aware of that.

I'm not happy with the current situation either. I would love to have a better standard for exporting differently transpiled code. But until we have something like that, I will continue to ship the latest valid EcmaScript syntax. For now [npm's package.json file](https://docs.npmjs.com/files/package.json) only officially supports the `main` and the `browser` field as entry points.  Even the `module` field which you are using is nothing official yet.

Despite the arguments I mentioned above, I think the most important thing as that transpiling from ES2018 to ES2015 is an option whereas transpiling from ES2015 to ES2018 is not possible. If I would transpile the code to some older EcmaScript version I would make it impossible for anyone who prefers to use the latest version to do so.

The reason why I think it is okay to require the users of this package to use a transpiler is that they need a bundler anyway to use this package which means there must be some build process in place already.

Again, I think this is not an ideal solution but it is the best solution I can currently think of.
