### ISSUE TITLE
How to include this library without a build step?

### ISSUE THREAD

**Issue by felix-voicehub** [chrisguttandin/standardized-audio-context#594]
Is it possible to use this library without a build step? Including the `bundle.js` leads to 
>Uncaught TypeError: _typeof is not a function

**Comment by chrisguttandin** [comment]
Hi @felix-voicehub,

although you closed this issue already, maybe this snippets helps: https://github.com/chrisguttandin/standardized-audio-context/issues/399#issuecomment-430820112. It shows how to load the library with jspm.io.
