### ISSUE TITLE
Unable to find native AudioParam on connection

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#642]
I'm trying to integrate standardized-audio-context into Tone.js, but i'm getting an issue when i try to use it in a simple Oscillator: `Uncaught Error: A value with the given key could not be found.`

Here's how i reproduced it: https://codesandbox.io/s/sharp-currying-k9v9y

For context, the oscillator uses two ConstantSourceNodes connected to the `frequency` and `detune` of the OscillatorNode. it seems to cause an issue when the constant source is connected to the AudioParam. It is unable to resolve the native AudioParam in the WeakMap. Either the AudioParam has been already garbage collected, which seems unlikely, or possibly it was not added. 

Thanks for your help!

**Comment by chrisguttandin** [comment]
Hi Yotam, I'm not entirely sure if that is the problem, but maybe you get the error because you're trying to mix native AudioParams with things exposed by standardized-audio-context. If that's the case then this is currently not supported. Everything within an AudioContext from standardized-audio-context needs to be from standardized-audio-context. I did this because it is easier to reason about and it is actually a requirement by the spec. But maybe this is not what you're trying to do. Please let me know if that's the case.

Anyway, many thanks for raising this issue because this is clearly not a very helpful error message.

**Comment by tambien** [comment]
What i'm confused about is that once the context is set, everything should be using standardized-audio-context for every object and AudioParam, so the OscillatorNode that's created and the ConstantSourceNodes are all created from the passed in AudioContext (standardized-audio-context). 

I'm going to see if i can try to verify the issue without Tone.js.

**Comment by chrisguttandin** [comment]
I took another look at your example today and this time I have another assumption which can of course be false again. :-)

A few days ago I fixed a bug which was caused by duplicate connections. Calling `a.connect(b)` more than once wasn't handled correctly. I haven't published [the fix](https://github.com/chrisguttandin/standardized-audio-context/commit/6db941540c62a9f99da6e94b9c87efecff01e7ee) yet to npm as I was hoping to get some more breaking changes done before the next major release. But this is done now and I will publish the new version now. Hopefully this will fix your problem as well.

**Comment by chrisguttandin** [comment]
Unfortunately that didn't fix the problem. I tried to download the example to further debug it. I noticed that it uses Tone at version 12 instead of 13. Is there a particular reason for that or should I better update Tone to debug with the latest version?

**Comment by tambien** [comment]
oh! the version that i’ve been testing with is the latest on the typescript branch. should be tone@^14.2.10. i’ve been making some preparations on that branch for using standardized-audio-context like removing all references to `arg instanceof AudioParam` to make it more compatible with this lib.

**Comment by chrisguttandin** [comment]
Yes, you're right it's tone@14.x.x. I was just confused as npm said it's outdated.

Do you maybe convert the AudioParam somewhere? Maybe by destructuring it or doing something similar. When I inspect the AudioParam that throws the error with the dev tools I'm missing the getters and setters. It somehow became a plain object. Do you have an idea why that's the case?

**Comment by chrisguttandin** [comment]
I think it is `optionsFromArguments()` which performs a deep merge. When I inspect an AudioParam before it goes into the `Param` constructor everything looks okay. But afterwards it's just a plain object.

I wonder what would be the easiest way to avoid that. It would for example be possible to define an AudioParam as class instead. Right now it's just an object with some getters and setters: https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/audio-param-factory.ts.

**Comment by tambien** [comment]
thanks for looking into that. that’s helpful! i think i know how to fix it. will try something tmrw and get back to you

**Comment by tambien** [comment]
I changed the deepMerge code in `optionsFromArguments` to not merge AudioParam, AudioNode and AudioBuffer, and instead just set them directly. This seems to have fixed the problem. I'm going to continue to integrate standardized-audio-context and let you know if i've got other issues. thanks for your help on this

**Comment by chrisguttandin** [comment]
Thanks for letting me know. I'm glad it works now.

I wonder if `isAudioParam()` and `isAudioNode()` should not be part of this library instead. It would be very easy to maintain for example a WeakSet for AudioParams and AudioNodes to identify them reliably afterwards.

What do you think?

**Comment by tambien** [comment]
you mean using an `isAudioParam` function from standardized-audio-context instead? i'd be happy to use that since i don't think that my implementation is 100% reliable. seems pretty easy to trick my version of `isAudioParam` by just creating an object with some similar attributes.

**Comment by chrisguttandin** [comment]
standardized-audio-context has already an [`isAudioNode()`](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/guards/audio-node.ts) and an [`isNativeAudioNode()`](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/guards/audio-node-output-connection.ts) function but these are only TypeScript guards which check for a certain property to distinguish an `AudioNode` from an `AudioParam`. I think they should only be used internally as they could be fooled very easily in JavaScript code.

But standardized-audio-context has also some WeakMaps (`AUDIO_NODE_STORE`, `AUDIO_PARAM_AUDIO_NODE_STORE`, `CONTEXT_STORE`) which store every created `AudioNode`, `AudioParam` and `AudioContext`. It therefore would be possible to expose to functions like this:

```typescript
export const isAnyAudioParam = (anything: any): anything is AudioParam | TNativeAudioParam => {
    return (AUDIO_PARAM_AUDIO_NODE_STORE.has(anything) || anything instanceof window.AudioParam);
};
```

Similar functions could be created for `AudioNodes` and `AudioContexts`. Would that be helpful?

**Comment by tambien** [comment]
exposing that API would be really helpful. I think the ones that i'd need are isAudioParam, isAudioNode, isAudioContext and isOfflineAudioContext. thanks!

**Comment by chrisguttandin** [comment]
I just published v21.1.0 which contains the first of those helper functions as a test. I called it `isAnyAudioNode()` to differentiate it from the internal TypeScript guard. I used this naming convention in some other cases already. Anything that starts with `Any...` can also be a native thing.

Can you please take a look at the [README](https://github.com/chrisguttandin/standardized-audio-context#isanyaudionode) and tell me if that makes sense to you?

**Comment by tambien** [comment]
just tested it out and it looks good to me! the README description looks good also.

**Comment by chrisguttandin** [comment]
v21.2.0 has now also [`isAnyAudioContext()`](https://github.com/chrisguttandin/standardized-audio-context#isanyaudiocontext), [`isAnyAudioParam()`](https://github.com/chrisguttandin/standardized-audio-context#isanyaudioparam) and [`isAnyOfflineAudioContext()`](https://github.com/chrisguttandin/standardized-audio-context#isanyofflineaudiocontext).

**Comment by chrisguttandin** [comment]
Yes an instanceof check will work.

The AudioBuffer implementation is very dirty because by definition an AudioBuffer is the only thing which can be shared across different (Offline)AudioContexts. The constructor in particular is doing something which should normally never be done: https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/audio-buffer-constructor.ts#L89 :-)

I did all this to make the following work:

```js
import { AudioBuffer } from 'standardized-audio-context';

const nativeAudioContext = new AudioContext();
const nativeAudioBufferSourceNode = new AudioBufferSourceNode(
    nativeAudioContext,
    { buffer: new AudioBuffer({ length: 1, sampleRate: 44100 }) }
);
```

**Comment by chrisguttandin** [comment]
After writing the message above yesterday I realized that it is unfortunately not that easy. Up to now we have the following behavior which I think is super confusing.

```js
import { AudioBuffer as StdAudioBuffer } from 'standardized-audio-context';

const nativeAudioBuffer = new AudioBuffer({ length: 1, sampleRate: 44100 });

// This seems reasonable to me:
console.log(nativeAudioBuffer instanceof AudioBuffer); // true
console.log(nativeAudioBuffer instanceof StdAudioBuffer); // false

const stdAudioBuffer = new StdAudioBuffer({ length: 1, sampleRate: 44100 });

// But I think this is confusing:
console.log(stdAudioBuffer instanceof AudioBuffer); // true
console.log(stdAudioBuffer instanceof StdAudioBuffer); // false
```

[I changed that now](https://github.com/chrisguttandin/standardized-audio-context/commit/0f6e31417869dfdc51c4e3d0705d999f6ee4e1ef) that an AudioBuffer created with standardized-audio-context also returns true when doing an instanceof check with the constructor exported by standardized-audio-context.

Only the result of the last console.log() from the example above will change when using v21.2.1 (yet to be released) onwards.

```js
// ...
console.log(stdAudioBuffer instanceof AudioBuffer); // true
console.log(stdAudioBuffer instanceof StdAudioBuffer); // true
```

I hope this makes sense to you as well.
