### ISSUE TITLE
DelayNode should be able to have cyclic connection

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#646]
According to [the spec](https://webaudio.github.io/web-audio-api/#AudioNode-methods), connections are allowed to be cyclic as long as that cycle contains a DelayNode. 

>an AudioNode may connect to another AudioNode, which in turn connects back to the input or AudioParam of the first AudioNode. This is allowed only if there is at least one DelayNode in the cycle or a NotSupportedError exception MUST be thrown.

[Here's a minimal example](https://codesandbox.io/s/delay-node-cycling-connection-i0pz1) of a cyclic connection which includes a DelayNode which throws a NotSupportedError.

**Comment by chrisguttandin** [comment]
Many thanks again. This was another subtle bug that lured under the surface. Cycles which were closed with a DelayNode were detected as false positives. This should be fixed now.

**Comment by chrisguttandin** [comment]
This is now released with v21.0.3

**Comment by tambien** [comment]
Thanks for the quick update, i found one more issue with this, which is that it does not render in the OfflineAudioContext. 

https://codesandbox.io/s/delay-node-cycling-connection-offline-v8tnn

The `startRendering()` Promise never resolves in the OfflineAudioContext with a cyclic connection

**Comment by chrisguttandin** [comment]
Hi @tambien, thanks for catching this.

For some reason there was not a single test in the whole test suite which covered cycles. And of course they did not work. :-( I added a test now and fixed the DelayNode. However I think there will be other edge cases as the rendering of an OfflineAudioContext is very complex.

The ScriptProcessorNode doesn't reliable get called in [Safari](https://github.com/chrisguttandin/standardized-audio-context/blob/master/test/expectation/safari/any/offline-audio-context-constructor.js#L758) which means the workarounds for the missing AudioNodes can't use it. Instead they work be splitting the graph. Everything which is an input to one of those AudioNodes gets first rendered down to an AudioBuffer. That AudioBuffer is then used to apply the workaround and when that's done it gets fed into the remaining graph as input. This does of course create a whole new category of problems. So there is a good chance that you run into some of those. Please let me know when that happens.

**Comment by chrisguttandin** [comment]
The fix was published with v21.1.0.

**Comment by tambien** [comment]
Thank you! The patch fixed the minimal example, but still getting this issue when i use it with Tone.js which is composed of a few more nodes and node-types:

https://codesandbox.io/s/delay-node-cycling-connection-offline-3gmyp

**Comment by chrisguttandin** [comment]
When I open the link above I get a TypeScript error because of an unused variable. When I remove the variable declaration, I don't see any other error.

https://codesandbox.io/s/delay-node-cycling-connection-offline-pf76t

**Comment by tambien** [comment]
if you comment out `import { OfflineAudioContext } from "standardized-audio-context"` you'll see it renders an AudioBuffer, but when it's left in, it doesn't render an AudioBuffer

**Comment by chrisguttandin** [comment]
Ah, sorry. I forgot that I have to watch out for endless loops. I will take another look trying to find out why the promise never resolves.

**Comment by chrisguttandin** [comment]
Do you know what the graph looks like that the FeedbackDelay is building? I tried to analyze it with Audion but the result is very confusing.

**Comment by tambien** [comment]
So this is the gist: 

![image](https://user-images.githubusercontent.com/1323402/63546430-ab770a80-c4de-11e9-9d7b-6bba9a25d0f6.png)

The lower half is the feedback delay, you can see the delay nodes and gains with the feedback loop. The upper half is the dry/wet knob using a Tone.CrossFade. [Here's a little ASCII diagram about how that works](https://github.com/Tonejs/Tone.js/blob/typescript/Tone/component/channel/CrossFade.ts#L16-L28). It's composed of a StereoPannerNode, a ChannelSplitter and a BufferSourceNode (which is just outputting a constant value of `1` on loop).

**Comment by chrisguttandin** [comment]
Thanks a lot for the detailed explanation. Apparently it looks like we need to make sure all AudioNodes work well with cycles (not only DelayNodes) as we don't know which type of AudioNode will close a cycle.

I will modify all nodes as I did with the DelayNode. Let's see if that helps.

**Comment by chrisguttandin** [comment]
Version 21.1.1 does now resolve the Promise with an AudioBuffer. Does it contain the expected signal?
