### ISSUE TITLE
Can't create AudioBuffer in @21.2.1

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#665]
I think should be allowed: 

```typescript
import { AudioContext } from "standardized-audio-context";

const ac = new AudioContext();

ac.createBuffer(2, 44100, 44100);
```

but it throws an error: 

`TypeError: Cannot call a class as a function`

Seems related to our discussion in #642 

example: https://codesandbox.io/s/cant-create-audio-buffer-pfz6x

**Comment by chrisguttandin** [comment]
Sorry for the glitch. I forgot that the helper introduced by babel uses an instanceof check as well. I therefore updated the custom instanceof check to include the default one as well.

**Comment by chrisguttandin** [comment]
Version v21.2.2 contains the fix. And v21.2.3 has an additional check to make sure the correct error message is thrown when trying to create an AudioBuffer with the new keyword.

**Comment by tambien** [comment]
thanks!
