### ISSUE TITLE
AudioWorkletNode in Firefox throwing `Unsupported Operation` and `currentFrame` is not defined

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#697]
Here's a basic AudioWorkletNode which runs in Firefox and not Chrome. I initially put this example together because firefox would throw an error that 'currentFrame' is not defined. That error does not happen in Chrome.

The second issue that came up while i was creating a minimal test version of the issue was that if the AudioWorkletNode has 0 inputs and no parameters, you get an `Unsupported Operation` error which seems to be coming from the fact that it's trying to create an OfflineAudioContext with 0 channels. 

https://codesandbox.io/s/offline-worklet-rendering-r4zmp

**Comment by chrisguttandin** [comment]
Thanks for reporting this. It were indeed two different bugs.

The first one was that the `process()` function of an `AudioWorkletProcessor` was not wrapped in the function which exposes `currentFrame` and `currentTime`.

The other one was the problem that you already discovered. When an `AudioWorklet`had no inputs it was still tried to render them which is not the case anymore.

I will publish the fixes with the next major release.
