### ISSUE TITLE
Safari chained connect issue

### ISSUE THREAD

**Issue by JackCA** [chrisguttandin/standardized-audio-context#753]
I just widely released code that runs off of `standardized-audio-context` (thank you!) -- however, I'm seeing a lot of exception being reported for [this line ](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/native-wave-shaper-node-faker-factory.ts#L163) for Safari versions 12 and 11.

I've made one of the [Sentry exceptions public](https://sentry.io/share/issue/bbbedc6347d842ecaa56ac6b76cf1c9f/) which may help debug.

**Comment by chrisguttandin** [comment]
Hi Jack, thanks for the detailed report. Unfortunately this is expected as Safari 11 and 12 are not supported anymore.

I try to support the latest two versions of each browser which is 12.1 and 13 in case of Safari right now. Safari v12.1 introduced support for chainable connect() calls.

The reason behind that strategy is that I want to make sure the library doesn't grow indefinitely in size. So whenever something gets native support and a workaround becomes obsolete I do remove it. This is always a major version change of standardized-audio-context.

You can check if a browser is supported or not by using the [`isSupported()`](https://github.com/chrisguttandin/standardized-audio-context#issupported) function. That should hopefully eliminate the errors.

**Comment by JackCA** [comment]
Gotcha, that's what I suspected. I already have a custom "your browser is not supported" message on my site, so I'll used your`isSupported` function to show it for these users.

Thanks!

**Comment by Christilut** [comment]
@JackCA I need to support iOS Safari 12 as well, quite a lot of users are still on it.

What is the suggested way to do this? Downgrade to an older version of this package or something else?

Making an exception for Safari 12 is kind of hard in my code now because I'm not actually sure how smart/easy it would be to mix the SourceNodes of this package and the native ones.
