### ISSUE TITLE
Please add a distribution file

### ISSUE THREAD

**Issue by Hlsgs** [chrisguttandin/standardized-audio-context#762]
I find myself unable to compile a workable file, having tried with `rollup`. Please add a dist file.

**Comment by chrisguttandin** [comment]
Hi @Hlsgs, I'm not sure what you're actually trying to do. The [package distributed on npm](https://www.npmjs.com/package/standardized-audio-context) contains various "dist" files.

Some time ago I created a [demo project](https://github.com/chrisguttandin/standardized-audio-context-demo) which shows how to use standardized-audio-context with webpack.

In case you want use standardized-audio-context in your own package it might be helpful to take a look at [standardized-audio-context-mock](https://github.com/chrisguttandin/standardized-audio-context-mock) which does exactly that. It uses rollup to bundle the dependencies.

**Comment by Hlsgs** [comment]
Hi @chrisguttandin,
The files in teh NPM package locat3ed under `/build` are unusable as is as stated in #399 and I can't figure out from teh other mentioned projects how exactly I would go about obtaining an upto date ES5 full version of SAC that I could just drop in a project. It would be very helpful for people like me who are not yet on the Webpack/modules bandwagon if you had dist files in your project and/or distributed to a CDN.

**Comment by chrisguttandin** [comment]
Okay, at least I have a better idea now what you're up to. The provided projects do not match your use case since I had no idea what you are planning.

I'm curious why the provided solution in #399 doesn't work for you? It's not ES5 but any browser that is supported by standardized-audio-context should support the import syntax as well.

**Comment by chrisguttandin** [comment]
Hi @Hlsgs, I added an explanation to the README which shows how `standardized-audio-context` can be used by loading the bundle directly from jspm. I hope that solves your use case. Please let me know if it doesn't.
