### ISSUE TITLE
PannerNode does not pan in Safari

### ISSUE THREAD

**Issue by kirbysayshi** [chrisguttandin/standardized-audio-context#819]
Hello! I'm not sure if this is a bug, or a known discrepancy, especially considering https://github.com/chrisguttandin/standardized-audio-context/issues/444.

If you look at and listen to some sample code: https://codesandbox.io/s/web-audio-x-platform-test-xvcdt (click "Test Left Panner" under the Standardized Web Audio Test)

In Safari, PannerNode from standardized-audio-context does not spatialize the audio at all, and actually sounds at least twice as loud as calling `setPosition` on a native web audio panner node.

Is the intent to just ensure the APIs are present, but potentially non-functional in standardized-audio-context? If so, a note in the documentation specifically about the PannerNode might prevent future users of standardized-audio-context from spending the time I spent looking into this 🤣 . Especially since the deprecated yet present `setPosition` API is explicitly not included in `IPannerNode`, which means that programming a workaround for safari users (especially mobile safari) is effectively impossible!

**Comment by chrisguttandin** [comment]
Hi @kirbysayshi, thanks for filing this bug. It is certainly not meant to be like that. The goal of this library is to provide a consistent behavior across all browsers. Of course that is not 100% possible because every browser is a little different but we can at least try. :-)

I was able to identify the bug so far but unfortunately fixing it is not so easy. I will try to do it this weekend.

**Comment by kirbysayshi** [comment]
@chrisguttandin Hey! sorry if I sounded at all disparaging towards standardized-audio-context in my bug report. I'm really happy this project exists! And thanks for trying to fix a pretty tricky platform inconsistency.

I'll update my test sandbox so it uses the newest standardized audio context too :D

**Comment by chrisguttandin** [comment]
No worries. It didn't sound disparaging to me. I was happy for the detailed bug report.

I haven't published the changes to npm yet. But I'm doing it right now. I will tell you once it's done.

**Comment by chrisguttandin** [comment]
Hi @kirbysayshi, v24.0.1 which contains the fix is available on npm now. I updated your example as well to double check that it actually works: https://codesandbox.io/s/web-audio-x-platform-test-1det5.

**Comment by kirbysayshi** [comment]
@chrisguttandin great, looks good! Thanks for your hard work on implementing this!

**Comment by chrisguttandin** [comment]
You're welcome. Let me know if you run into any other issues.
