### ISSUE TITLE
createMediaStreamDestination available in edge

### ISSUE THREAD

**Issue by CoreyCole** [chrisguttandin/standardized-audio-context#833]
I noticed in the readme, it states:
> `createMediaStreamDestination()` is not implemented in Edge and unfortunately it is very complicated (if not impossible) to polyfill

I've just checked caniuse.com and it looks like this api is available in [Edge v80](https://caniuse.com/#search=createMediaStreamDestination)

Can this polyfill include `createMediaStreamDestination()` now that it has been implemented in Edge?

**Comment by chrisguttandin** [comment]
Hi @CoreyCole,

I'm indeed planning to add the `createMediaStreamDestination()` function now. It was requested many times. @liberatomota-itcenter, for example, asked for it in #283 almost 2 years ago.

I plan to add it as part of a feature release at first. It would then throw a NotSupportedError in older browsers (aka Edge v18). I think it is necessary to continue supporting Edge v18 for a bit longer. Normally I drop support for a browser when there are two newer versions available but I'm not sure if that works for Edge in that case.

Are you by chance a Windows user? Did the update from v18 to v80 happen automatically?

**Comment by CoreyCole** [comment]
I'm not a windows user, but I found a forum thread that loosely implies the update was manual and users are able to downgrade from v80 back down to older versions: https://answers.microsoft.com/en-us/microsoftedge/forum/all/about-microsoft-edge-version-80036148-official/a6032bc0-c446-49b9-b74b-e25ccd3d4ff4

**Comment by chrisguttandin** [comment]
Yes, I'm afraid many people are still using Edge v18.

I just publish v24.1 which does now support the `createMediaStreamDestination()` method and the `MediaStreamAudioDestinationNode` constructor. It will throw a `NotSupportedError` in Edge v18.
