### ISSUE TITLE
Error in getUserMedia in iOS Safari

### ISSUE THREAD

**Issue by nchase** [chrisguttandin/standardized-audio-context#871]
Hi 👋

I'm wondering if I might be doing something wrong, or if this is a legitimate bug. 

I call `getUserMedia` like so, and it seems to work everywhere except for iOS Safari:

```js
var stream = await navigator.mediaDevices.getUserMedia({ audio: true });
```

In iOS Safari, my code throws an Error: 
```js
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'mediaStream.getAudioTracks')
```

The stack trace points to line 3 of `native-media-stream-audio-source-node-factory.js` as the problem line. I'd paste the stack trace in text, but Safari won't let me, so here's a screenshot:

<img width="872" alt="Screen Shot 2020-04-08 at 11 28 30 PM" src="https://user-images.githubusercontent.com/197309/78855074-f18ec900-79f0-11ea-9140-4983efc2e5fb.png">

Thanks (as always) for the awesome library and your awesome work.

**Comment by chrisguttandin** [comment]
Hi Noah,

is it possible that `getUserMedia()` in Safari is still callback-based?

```js
navigator.mediaDevices.getUserMedia({ audio: true }, (stream) => { }, (err) => { });
```

The `mediaStream` that you pass into the `MediaStreamAudioSourceNode` seems to be undefined for some reason.

**Comment by nchase** [comment]
Thanks as usual for the fast response – I think I have a few issues here. I'll close until/unless I come up with something more concrete.
