### ISSUE TITLE
OfflineAudioContext suspend/resume

### ISSUE THREAD

**Issue by 1valdis** [chrisguttandin/standardized-audio-context#883]
By specification, OfflineAudioContext has `suspend` (on itself) and `resume` (from `BaseAudioContext`) methods. They are currently natively available in Chrome. But this library, as I understand, has them for AudioContext only.
Edit: also there seemingly is no `length` property on it too.

**Comment by chrisguttandin** [comment]
The goal of this library is to provide a consistent experience across all supported browsers. Usually Chrome and Firefox are not the problem. It's mostly Safari which lacks behind. It's the same in this case. Safari doesn't support this feature. It has the methods but they don't work.

I can't think of a practical way to polyfill this feature for Safari. But I'm happy for any input on it. Please let me know if you have ideas how that could be done.

The `length` property is present. I somehow forgot to add it to the README. I will fix that. Thanks for making me aware of it.

**Comment by 1valdis** [comment]
> It's the same in this case. Safari doesn't support this feature. It has the methods but they don't work.

Firefox doesn't support it too. Which makes it almost Chrome exclusive despite being in the candidate recommendation. And I have no idea how to polyfill that too. You can close the issue then, I'm good with that it stays in repo history and people will find out why those methods are not there.

> The length property is present. I somehow forgot to add it to the README. I will fix that. Thanks for making me aware of it.

Ok, so it was only for Readme, good to know.

**Comment by chrisguttandin** [comment]
I added two expectation tests for Safari and Firefox which are supposed to break whenever there will be a change in their implementation of the Web Audio API. That way it will be unnoticed in case it ever happens.
