### ISSUE TITLE
TypeError: Failed to construct 'AudioWorkletNode': parameter 1 is not of type 'BaseAudioContext'

### ISSUE THREAD

**Issue by cutterbl** [chrisguttandin/standardized-audio-context#897]
Tried implementing an audioWorklet with SAC. My audioWorklet works fine with the browser native AudioContext (in Chrome), but when I tried to use the SAC AudioContect I received the following error when it tried to construct my AudioWorkletNode:

```
TypeError: Failed to construct 'AudioWorkletNode': parameter 1 is not of type 'BaseAudioContext'
```
Parameter 1 is the AudioContext object. In my example code I was using the following import

```
import sac from 'https://dev.jspm.io/npm:standardized-audio-context';
//...
const myCtx = new AudioContext();
```

**Comment by cutterbl** [comment]
Diving deep into your code shows me that you export your own `AudioWorkletNode`, as part of SAC. What isn't clear (or exported) is the `AudioWorkletProcessor` side of audioworklets? My current processor extends the `AudioWorkletProcessor` (which you do not seem to export). How do I implement my processor for use with SAC?

**Comment by chrisguttandin** [comment]
Hi Steve,

I tried my best to not modify any native object or prototype. In contrast to some other polyfills `standardized-audio-context` can be used in libraries without causing any side effects. The downside is that anything needs to be imported since nothing is available globally.

Your snippet from above would still use the native `AudioContext`. If you want to use the one from `standardized-audio-context` it needs to be referenced explicitly.

```js
import sac from 'https://dev.jspm.io/npm:standardized-audio-context';
//...
const myCtx = new sac.AudioContext();
```

However on the `AudioWorkletGlobalScope` (the thread on which the `AudioWorkletProcessor` runs) things are a bit different. It's not necessary to import anything over there.

I created a demo (https://github.com/chrisguttandin/standardized-audio-context-demo) which shows how `standardized-audio-context` can be used with an [`AudioWorklet`](https://github.com/chrisguttandin/standardized-audio-context-demo/blob/master/src/scripts/worklet.js).

Please let me know if that solves your issue.

**Comment by cutterbl** [comment]
Sorry, I didn't show where I was destructuring sac afterwards. Was also reviewing the code and saw where you export an `AudioWorkletNode`. So, trying to move forward...

Curiosity, does AudioContext.createGainNode() create your GainNode? (sure I'll find out shortly, but figured I'd ask...)

**Comment by chrisguttandin** [comment]
I'm not sure if that answers your question, but if you created an `AudioContext` with `standardized-audio-context` anything that it returns will be compatible.

The only things which work with a native `AudioContext` as well are `AudioBuffer`s. That's required by the spec.

**Comment by chrisguttandin** [comment]
But since this issue is about the `AudioWorkletNode` constructor can you please share your code which is supposed to create an `AudioWorkletNode`?

**Comment by cutterbl** [comment]
@chrisguttandin I got it working in a completely local example now. Here were those relevant bits:

```
import SoundTouchNode from '/SACSoundTouchNode.js';
import sac from 'https://dev.jspm.io/npm:standardized-audio-context';
const { AudioContext } = sac;
```

Then creating my context:

```
const setupContext = function () {
  audioCtx = new AudioContext();
  return audioCtx.audioWorklet
    .addModule('./js/soundtouch-worklet.js')
    .catch((err) => console.log(err));
};
```

And my `AudioWorkletNode`:

```
soundtouch = new SoundTouchNode(audioCtx, rawBuffer);
```

And created an SAC version of my SoundTouchNode:

```
import sac from 'https://dev.jspm.io/npm:standardized-audio-context';
const { AudioWorkletNode } = sac;
export default class SoundTouchNode extends AudioWorkletNode {
// ...
```

This is working fine now with the `AudioWorkletProcessor` I had already written.

I maintain the SoundTouchJS library, and currently writing in audioWorklet support. Now that I see this (above) implementation will work, I want to create an `SACSoundTouchNode` for export as well, but first have to get around [this bundling error](https://github.com/chrisguttandin/standardized-audio-context/issues/898) (Issue #898).

**Comment by cutterbl** [comment]
In the (attempted) bundle version of `SACSoundTouchNode` I'm doing a standard `import`

```
import { AudioWorkletNode } from 'standardized-audio-context';
```

**Comment by chrisguttandin** [comment]
I'm happy to hear that SoundTouch is getting an AudioWorklet implementation. I'm a fan. :-)

If you want to allow your user's to use the AudioWorklet directly with or without `standardized-audio-context` that's possible as well.

I created a limiter which does that which you could use as an example. https://github.com/chrisguttandin/limiter-audio-worklet.

**Comment by cutterbl** [comment]
Unfortunately it was requested to use SoundTouchJS, with worklet, directly with SAC, and the implementation I put together initially used the `AudioWorkletNode` `AudioWorkletProcessor` paradigm to match the documentation, so my bits are deeply tied together. Fairly easy to provide an SAC version of the Node, as long as I can resolve the build issue. My plan was to export both a native `AudioWorkletNode` and an SAC version (my `AudioWorkletProcessor` seemed to work with both locally).

**Comment by chrisguttandin** [comment]
Can we close that as well? I think it is closely related to #898.
