### ISSUE TITLE
'AutomationEventList' is not exported

### ISSUE THREAD

**Issue by cutterbl** [chrisguttandin/standardized-audio-context#898]
I am creating an audioWorklet implementation, and was asked to get it working with SAC. The implementation works fine with a browser native implementation of AudioContext (in Chrome).

In this version of my example, I attempted to bundle my `example.js`, and it immediately errored at SAC

```
import { AudioContext } from 'standardized-audio-context';
```

And the error:

```
[!] Error: 'AutomationEventList' is not exported by node_modules/automation-events/build/es5/bundle.js, imported by node_modules/standardized-audio-context/build/es2019/factories/audio-param-factory.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/standardized-audio-context/build/es2019/factories/audio-param-factory.js (1:9)
1: import { AutomationEventList } from 'automation-events';
```

**Comment by cutterbl** [comment]
I get this error from the bundler when attempting to import any SAC object.

**Comment by cutterbl** [comment]
For reference, I'm using SAC@24.1.7, and an `npm ls automation-events` shows it's version is 2.0.5.

**Comment by chrisguttandin** [comment]
I know it doesn't help but I use rollup in many projects and never experienced this. Do you mind sharing your project setup and rollup config?

**Comment by cutterbl** [comment]
rollup config `rollup.config.js`:

```
import path from 'path';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import babel from 'rollup-plugin-babel';
import clear from 'rollup-plugin-clear';
import { eslint } from 'rollup-plugin-eslint';
import cleanup from 'rollup-plugin-cleanup';
import pkg from '../package.json';

export default [
  {
    input: path.join(__dirname, '../src/index.js'),
    output: [
      {
        file: pkg.module,
        format: 'es',
        sourcemap: true,
        exports: 'named',
      },
    ],
    plugins: [
      clear({
        targets: [path.join(__dirname, '../dist')],
        watch: true,
      }),
      resolve({
        browser: true,
      }),
      commonjs(),
      eslint(),
      babel({
        runtimeHelpers: true,
        exclude: ['/node_modules/**'],
      }),
      cleanup(),
    ],
  },
];
```

file structure:
![Screen Shot 2020-04-29 at 9 36 41 AM](https://user-images.githubusercontent.com/666987/80608843-01506a80-89fd-11ea-8766-0a8b94d5e5da.png)

`package.json` script line:

```
"build": "rollup -c scripts/rollup.config.js && rollup -c scripts/rollup.worklet.config.js",
```
Full stacktrace from rollup
```
[!] Error: 'AutomationEventList' is not exported by node_modules/automation-events/build/es5/bundle.js, imported by node_modules/standardized-audio-context/build/es2019/factories/audio-param-factory.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/standardized-audio-context/build/es2019/factories/audio-param-factory.js (1:9)
1: import { AutomationEventList } from 'automation-events';
            ^
2: export const createAudioParamFactory = (addAudioParamConnections, audioParamAudioNodeStore, audioParamStore, createAudioParamRenderer, createCancelAndHoldAutomationEvent, createCancelScheduledValuesAutomationEvent, createExponentialRampToValueAutomationEvent, createLinearRampToValueAutomationEvent, createSetTargetAutomationEvent, createSetValueAutomationEvent, createSetValueCurveAutomationEvent, nativeAudioContextConstructor) => {
3:     return (audioNode, isAudioParamOfOfflineAudioContext, nativeAudioParam, maxValue = null, minValue = null) => {
Error: 'AutomationEventList' is not exported by node_modules/automation-events/build/es5/bundle.js, imported by node_modules/standardized-audio-context/build/es2019/factories/audio-param-factory.js
    at error (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:10120:30)
    at Module.error (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:14470:16)
    at handleMissingExport (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:14371:28)
    at Module.traceVariable (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:14849:24)
    at ModuleScope.findVariable (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:13415:39)
    at ReturnValueScope.findVariable (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:8664:38)
    at ChildScope.findVariable (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:8664:38)
    at ReturnValueScope.findVariable (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:8664:38)
    at ChildScope.findVariable (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:8664:38)
    at Identifier$1.bind (/Users/47056/Documents/Projects/SoundTouchJS/node_modules/rollup/dist/shared/rollup.js:9123:40)
```

**Comment by cutterbl** [comment]
Deeper look at the error, it appears that the `automation-events` is an external dependency of SAC, and the `AutomationEventList` isn't being bundled into the library?

**Comment by chrisguttandin** [comment]
Yes, `automation-events` is a dependency and it is not bundled. It's just referenced in the package.json file.

One thing I noticed is that rollup is picking the es2019 files of the `standardized-audio-context` build while it picks the es5 build of `automation-events`. This is a bit odd since I publish both modules with similar settings. The `module` property inside the package.json file points to the es2019 files whereas the main property points to the es5 files. Not sure if that helps, though.

**Comment by cutterbl** [comment]
Yeah, I would be working with the es2019 stuff, so not sure why it's pulling from the es5 build.js, other than that seems to be part of your es2019 object build. The working local examples all use that cdn point, which uses the es5 stuff, if I read correctly...

**Comment by cutterbl** [comment]
After a lot of testing and reading I still can't figure out what is happening. No matter what I do, Rollup always chooses the es5 implementation when trying to 'rollup' the SAC dependency, ignoring the `module`.

**Comment by chrisguttandin** [comment]
Maybe it works if you restrict the [`mainFields`](https://github.com/rollup/plugins/tree/master/packages/node-resolve#mainfields) to make sure it only uses `module` or `main` but doesn't mix them.

**Comment by cutterbl** [comment]
No, I tried that. I guess it only goes one level deep. It's not SAC itself, but the `automation-events` dependency. The compiler gets to that, and tries to use the es5 bundle of `automation-events`.

**Comment by chrisguttandin** [comment]
I think the [`browser`](https://github.com/rollup/plugins/tree/master/packages/node-resolve#browser) option overrides the `mainFields` option.

Can you try you removing the `browser` option and configure set the `mainFields` to `[ 'module', 'browser', 'main' ]`?

**Comment by cutterbl** [comment]
@chrisguttandin Well, that was the magic sauce... sort of.

I did this to create my `SACSoundTouchNode`:

```
import { AudioWorkletNode } from 'standardized-audio-context';
export default class SoundTouchNode extends AudioWorkletNode {
```
I can see your code for the SAC `AudioWorkletNode` in my bundled output. `createAudioWorkletNodeConstructor`, `getAudioWorkletProcessor`, `processBuffer`... all that jazz. In fact it added about 3000 lines of code.

Now that I have bundled in the SAC `AudioWorkletNode` though, it no longer runs the example. It gets into the `createAudioWorkletNodeConstructor` method and dies during `getNativeContext`. I see the SAC `AudioContext` being passed in to the method. But in the method itself it dies on `const nativeContext = contextStore.get(context);`, throwing the DOMException 'InvalidStateError'.

so close...

**Comment by cutterbl** [comment]
To add to the above, when I mouse over the `context` argument in Dev Tools, on that line I ref'd, it's showing what looks like an Empty WeakMap.

Side Note: Testing with unbundled custom Node. I have a `currentTime` prop on my custom WorkletNode. I'm seeing a `currentTime`, on the `AudioContext` that appears to pass through to my custom node. When I 'play' my audio it does not start at the beginning (maybe I need to change my property name).

**Comment by chrisguttandin** [comment]
The error that you're describing sounds like the `AudioContext` passed into the `AudioWorkletNode` was not created with `standardized-audio-context` or that the processor is not yet loaded. But I'm just guessing. It would be easier for me if you could point me to the code.

**Comment by chrisguttandin** [comment]
I think I found your code over here: https://github.com/cutterbl/soundtouchjs-sac-audio-worklet :-)

I guess the line which is causing the trouble is this one: https://github.com/cutterbl/soundtouchjs-sac-audio-worklet/blob/cb378c8b747aa455b39cdef096aaf93b3d042abc/public/example.js#L95

As I said this is going to fail since the `AudioContext` is native whereas the `AudioWorkletNode` is not. The `AudioContext` needs to be imported from `standardized-audio-context` as well to make the example work.

For my `limiter-audio-worklet` I solved that problem by exporting a factory function instead of the constructor. https://github.com/chrisguttandin/limiter-audio-worklet/blob/master/src/module.ts#L30

This makes it possible to use that package with or without `standardized-audio-context`.

To implement the same technique for the `SoundTouchNode` you could change [that part of your code](https://github.com/cutterbl/soundtouchjs-sac-audio-worklet/blob/cb378c8b747aa455b39cdef096aaf93b3d042abc/src/SACSoundTouchNode.js#L68) to something which looks more like this:

```js
export default fucntion createSoundTouchNode(
    audioWorkletNodeConstructor,
    context,
    arrayBuffer,
    options
) {
    class SoundTouchNode extends audioWorkletNodeConstructor {
        // ...
    }

    return new SoundTouchNode(context, arrayBuffer, options);
}
```

Users of your library can then either use it with `standardized-audio-context` ...

```js
import { AudioContext, AudioWorkletNode } from 'standardized-audio-context';

const audioContext = AudioContext();

audioContext.audioWorklet
    .addModule('./js/soundtouch-worklet.js')
    .then(() => {
        createSoundTouchNode(AudioWorkletNode, audioContext/*, ... other parameters */);
    });
```

... or without it which does of course require a browser with native support.

```js
const audioContext = AudioContext();

audioContext.audioWorklet
    .addModule('./js/soundtouch-worklet.js')
    .then(() => {
        createSoundTouchNode(AudioWorkletNode, audioContext/*, ... other parameters */);
    });
```

**Comment by cutterbl** [comment]
Ha! You beat me to it (a little). I posted that yesterday, and the example is copied from the other repo and hasn't been made to work yet. (to see the error I was talking about, you could look at this branch https://github.com/cutterbl/soundtouchjs-sac-audio-worklet/tree/feature/bundled, where I bundled AudioWorkletNode directly), and used the CDN sac in the example (since it's not compiled).

That said, your factory idea makes a whole lot of sense. I could do that instead, and let the user make the option. I'm going to try that out on the primary worklet (and give you credit :) )

**Comment by cutterbl** [comment]
Factory method worked like a charm! You are Da Man! You can [play with it here](https://github.com/cutterbl/soundtouchjs-audio-worklet). (Credit where credit is due, in the README)

**Comment by cutterbl** [comment]
Total side note: was looking at a few of your projects, and didn't know if you'd played with the `@rollup/plugin-typescript` yet. Pretty smooth.

**Comment by chrisguttandin** [comment]
I'm happy to hear that it works. Can we consider this issue as resolved?

Many thanks for the attribution. Can you please add the missing "h" to my name. I know it's a complicated one. :-)

I don't quite understand the comment about the `@rollup/plugin-typescript` package. Do you mind elaborating a bit?

**Comment by cutterbl** [comment]
Issue resolved. 

So sorry about the name. I try to be really careful about that. Knew I should've cut and paste.

If you look in the latest of `@soundtouchjs/audio-context`, and look at the build, you see where I have one rollup config file that builds two separate assets, converting my build to one command and allowing rollup to handle both. I don't use TS in my project, but I saw where you were running your es2019 build through the TS compiler and then moving to rollup to compile an es5 target. With that `@rollup/plugin-typescript` you could do a very similar thing through a single call to rollup. Fewer steps in Grunt. (just an idea...)

**Comment by chrisguttandin** [comment]
Oh thanks for the hint. I will definitely take a look. Simplifying the build task is always a hot topic. :-)
