### ISSUE TITLE
Support for AudioContext.getOutputTimestamp

### ISSUE THREAD

**Issue by cutterbl** [chrisguttandin/standardized-audio-context#909]
Doing some testing today, and found that SAC isn't currently supporting [AudioContext.getOutputTimestamp()](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/getOutputTimestamp). Reading the MDN documentation, this seems to be fairly widely supported by the browsers, and has become a standard part of the API. Are there plans to add this to SAC for parity?

**Comment by chrisguttandin** [comment]
Yes, `getOutputTimestamp()` is not yet supported. The browsers which don't have it yet are Safari and the pre-Chromium version of Edge which is still supported by `standardized-audio-context`. There is a test for each browser which is meant to fail once it becomes supported natively.

https://github.com/chrisguttandin/standardized-audio-context/blob/master/test/expectation/edge/legacy/audio-context-constructor.js#L992

https://github.com/chrisguttandin/standardized-audio-context/blob/master/test/expectation/safari/any/audio-context-constructor.js#L1357

I will drop support for the old Edge with the next major release but I have no idea how this could be implemented for Safari. Do you have any ideas?

**Comment by cutterbl** [comment]
Yeah, I was just looking over the Safari stuff. I don't see an easy way to backfill the functionality.

**Comment by chrisguttandin** [comment]
There are some other parts of the API which can't really be implemented in some browsers. The `MediaElementAudioSourceNode` is one of those things. It throws a `NotSupportedError` in older versions of Edge. We could do a similar thing for `getOutputTimestamp()`.
