### ISSUE TITLE
Unable to connect IAudioNode to IAudioParam

### ISSUE THREAD

**Issue by bobdamit** [chrisguttandin/standardized-audio-context#921]
Hello,
Unless I am not understanding something, it seems that the overload of connect() which connects to an IAudioParam is not implemented. I am trying to implement an LFO for a filter or gain. 

I see these in the interface:

`connect<U extends TContext, V extends IAudioNode<U>>(destinationNode: V, output?: number, input?: number): V;`
and
`connect(destinationParam: T, output?: number): void;`

destinationParm is of type T which is 
`T extends TContext> extends TNativeEventTarget`

The disconnect method DOES have the third overload for disconnecting from an IAudioParam:
`disconnect(destinationParam: IAudioParam, output?: number): void;`

This is with latest version standardized-audio-context@24.1.13

**Comment by chrisguttandin** [comment]
Hi @bobdamit, thanks for reporting this. The interface definition was out of sync with the implementation: https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/audio-node-constructor.ts#L595

I will publish an updated version later today.

**Comment by chrisguttandin** [comment]
[v24.1.14](https://github.com/chrisguttandin/standardized-audio-context/releases/tag/v24.1.14) contains the fix. Please let me know if you experience any further issues and thanks again for reporting this.

**Comment by bobdamit** [comment]
@chrisguttandin , thank you so much for the quick turnaround.  The update is working perfectly!  I have successfully modulated a filter detune param with an oscillator and all is working as expected.
-Bob

**Comment by chrisguttandin** [comment]
I'm happy to heat that.
