### ISSUE TITLE
Cannot map createMediaElementSource

### ISSUE THREAD

**Issue by stephenwade** [chrisguttandin/standardized-audio-context#927]
I tried to use `map` to create several media element source nodes, but this silently fails. The only thing I see in the JavaScript console is "Uncaught DOMException".

I am using Google Chrome 81 on macOS Catalina 10.15.4.

Minimal test case:

```html
<!DOCTYPE html>
<html>
  <body>
    <audio id="audio1"></audio>
    <audio id="audio2"></audio>

    <script type="module">
      import { AudioContext } from 'standardized-audio-context';

      const ctx = new AudioContext();

      const audioElements = [audio1, audio2];
      const tracks = audioElements.map(ctx.createMediaElementSource);
    </script>
  </body>
</html>
```

(For a workaround, I used `forEach` to append to an empty array:)
```javascript
const tracks = [];
audioElements.forEach(audio => {
  tracks.push(ctx.createMediaElementSource(audio))
});
```

**Comment by chrisguttandin** [comment]
Hi @stephenwade,

what do you mean by it fails silently? Does the code execution continue?

The error that you get is somewhat expected. `createMediaElementSource()` needs to be called on the `MediaStreamAudioSourceNode`. It should work when you do it like this:

```js
const ctx = new AudioContext();
const audioElements = [ new Audio(), new Audio() ];
const tracks = audioElements.map((audio) => ctx.createMediaElementSource(audio));
```

You could also use `bind()`:

```js
const ctx = new AudioContext();
const audioElements = [ new Audio(), new Audio() ];
const tracks = audioElements.map(ctx.createMediaElementSource.bind(ctx));
```

**Comment by stephenwade** [comment]
The code execution stops.

Ohhhhhh, that makes sense - by just referencing the function in `map` without actually calling it, I lose the context.

Thanks for the reply. I just verified that it works fine when I call it like you suggested.
