### ISSUE TITLE
iOS 12.1: TypeError: undefined is not an object (evaluating 'n.connect(i).connect')

### ISSUE THREAD

**Issue by Christilut** [chrisguttandin/standardized-audio-context#950]
I'm getting this error with iOS 12.1:
```
TypeError: undefined is not an object (evaluating 'n.connect(i).connect')
```

This is from a browserstack device, user agent:
```
"Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1"
```

![image](https://user-images.githubusercontent.com/3471363/85200111-ef03f600-b2f4-11ea-82be-c7cf0bd77c7a.png)

My guess is that it happens on these lines (only place I use `connect`):
```js
      this.source.connect(this.gain)
      this.gain.connect(this.audioContext.destination)
```

**Comment by chrisguttandin** [comment]
Hi @Christilut, this looks as if the browser doesn't support chaining `connect()` calls which are used under the hood.

I'm curious, what's the result reported by `isSupported()` on that browser?

**Comment by Christilut** [comment]
I tried that on there and it returned `false`. But the docs say 12.1 is supported which is why I made this bug report.

**Comment by chrisguttandin** [comment]
Would it be easy for you to run the same test on a Desktop Safari at version 12.1? I wonder if version 12.1 means something different on iOS and macOS.

**Comment by Christilut** [comment]
Just ran it on browserstack. This time it returned `true`. 

macOS Mojave: Safari 12.1

![image](https://user-images.githubusercontent.com/3471363/85200652-9551fa80-b2f9-11ea-815f-b54631823464.png)

**Comment by chrisguttandin** [comment]
Thanks, a lot.

I think the reason is that iOS 12.1 did not have Safari 12.1. Safari 12.1 was shipped with iOS 12.2.

https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes?language=objc
https://developer.apple.com/documentation/safari_release_notes/safari_12_release_notes?language=objc

**Comment by Christilut** [comment]
Does this version fall in the scope of this package then? Looks like it's Safari 12.0 so I guess not. 

What's the workaround if I do want to support older devices like that?

**Comment by chrisguttandin** [comment]
If I recall correctly v21 was the latest version that supported Safari v12.

**Comment by Christilut** [comment]
Thanks, I'll see if reverting to that is a solution for me.

Also, I was just trying v21 on a new iphone with this useragent:
```
"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1"
```
And isSupported comes up with false. Is that expected?

**Comment by chrisguttandin** [comment]
No, theoretically that shouldn't happen. But when v21 was the current version, Safari v13 wasn't around yet. I don't know what the error is to be honest.

**Comment by Christilut** [comment]
I've solved my situation with the v21 version. Seems to do everything I need. Except that Safari 12.0 doesn't autoplay which Safari 13 does do. 

Just a bit of feedback: I do find a bit weird that this package doesn't support older versions. I get that it isn't a polyfill package but it makes having to support older versions quite complex. I'm lucky that v21 does everything in my situation but if it didn't support a new version of another browser, then it would make using this package difficult.

**Comment by chrisguttandin** [comment]
Thanks for sharing your opinion. A main goal of this project is to avoid stale code. In general I try to wait some time before removing support for outdated browsers. But in the end I'm hoping to just re-export the global `AudioContext` from this package. But this will for sure not happen anytime soon. :-)

Anyway, I would love to support something like browserlist to build custom versions of this package. But this is nothing I can deliver and maintain in my free time.

**Comment by Christilut** [comment]
I understand. And I'm already super happy I found this package. I finished my app in Chrome before starting to look at Safari, and well... You know how it goes then :)
