### ISSUE TITLE
Error: Missing the native AudioContext constructor.

### ISSUE THREAD

**Issue by dbads** [chrisguttandin/standardized-audio-context#951]
Hi,
I am getting the following error on initializing the audio context?

/node_modules/standardized-audio-context/build/es5/bundle.js:964
            throw new Error('Missing the native AudioContext constructor.');
                  ^
Error: Missing the native AudioContext constructor.

I am not sure what to do?

**Comment by chrisguttandin** [comment]
Hi @dbads, the error sounds as if you're using this package outside of the browser. Is that the case?

standardized-audio-context requires the native Web Audio API to be present in order to do it's job.

**Comment by dbads** [comment]
@chrisguttandin yes, I am using it in one of my node-express projects. How to make it work then?

**Comment by chrisguttandin** [comment]
In that case standardized-audio-context might not be the right tool. May I ask what you are using it for in an express server?

There are other packages which are (as far as I know) unmaintained now which aimed to bring the Web Audio API to Node.js. These are https://www.npmjs.com/package/web-audio-api and https://www.npmjs.com/package/web-audio-engine. Maybe these cover your use case.

**Comment by dbads** [comment]
@chrisguttandin Actually, not exactly for in an express server but I am writing a script where I want some sound notifications on different results achieved while the script is running or notification if it breaks due to bad network or something else. I want to keep track of what's happening in the script while working on something else parallelly.

Thanks for suggesting suitable libraries, I will have a look.

**Comment by chrisguttandin** [comment]
Thanks for providing more details. I think standardized-audio-context is probably not the right tool for that task. It's meant to run in the browser and needs at least some sort of native implementation to work correctly. I will therefore close the issue for now.

Feel free to reopen it if I misunderstood your comment above.

**Comment by jgentes** [comment]
For what it's worth, I also tried to get this module working in Node. In fact that's what I thought it did.. as I can just use the Web Audio API directly from the browser. It may be beneficial to new users to indicate that this package is only for browsers and not to provide a standardized way of implementing the web audio api across server & client environments, which it is easy to assume it does.

**Comment by chrisguttandin** [comment]
Sorry for the confusion. The description of the readme already says that it is a "cross-browser implementation". Do you have a suggestion how that could be changed to make it more explicit that it doesn't work with Node.js?

**Comment by jgentes** [comment]
No problem, it would have been great to see it working in Node :)

I think the goal is unclear - it says 'A cross-browser implementation of the AudioContext which aims to closely follow the standard.' and 'One of the goals of standardized-audio-context is to only implement missing functionality and to avoid rewriting built-in features whenever possible.'

I would perhaps describe the goal as something like 'standardized-audio-context solves the problem of inconsistent AudioContext API support across different browsers (Chrome, FF, Edge, Safari, etc)` and maybe making a separate `Note: This does not provide AudioContext support within Node.js'

Good work, I think the node support could be achieved using puppeteer, but that's a pretty heavy-handed solution and audio support for headless chrome is a bit sketchy still.

**Comment by chrisguttandin** [comment]
Thanks for your suggestions. I made a few updates to the readme.

https://github.com/chrisguttandin/standardized-audio-context/commit/789313a7634b8bc0a6143ec0087d6714e91edffc
https://github.com/chrisguttandin/standardized-audio-context/commit/9c705bd2e5d8a774b93b07c3b203c8f343737988
