### ISSUE TITLE
macos Safari:TypeError: undefined is not an object (evaluating 'nativeAudioScheduledSourceNode.connect(nativeGainNode)') 

### ISSUE THREAD

**Issue by TaoJinjin-Thomas** [chrisguttandin/standardized-audio-context#952]
I am using v14.7.39 Tonejs which require standardized-audio-context. And the safari throws this error when initial the page. But chrome and firefox has no problem
<img width="722" alt="Screen Shot 2020-08-17 at 6 16 13 PM" src="https://user-images.githubusercontent.com/17539265/90387146-3bcb3980-e0b8-11ea-92ed-5ee111d1b37e.png">

**Comment by TaoJinjin-Thomas** [comment]
Hope can receive your response, it will be very helpful. I am currently writing a DAW program.

**Comment by chrisguttandin** [comment]
The error message looks like you're using a version of Safari (anything below v12.1) which is not supported anymore. Is that possible?

**Comment by TaoJinjin-Thomas** [comment]
I see. I should be the old safari issue

**Comment by chrisguttandin** [comment]
Alright, I'll close this issue then. Let me know if you run into any issues with the currently supported versions of Safari.
