### ISSUE TITLE
audio not playing in ios safari mobile 13.6.1 

### ISSUE THREAD

**Issue by 0crypto0** [chrisguttandin/standardized-audio-context#953]
audio is not working on mobile ios latest version.

this.audioContext = new AudioContext();
          this.audioTrack = this.audioContext.createMediaElementSource(this.audioElement);
          this.gainNode = this.audioContext.createGain();
          this.audioTrack.connect(this.gainNode);
          this.gainNode.connect(this.audioContext.destination);
          if (this.isTherapist) {

**Comment by chrisguttandin** [comment]
Hi @0crypto0,

can you please provide further details? Do you get any errors? Does the `audioElement` play one its own without using an `AudioContext`? What state is the `AudioContext` reporting?

**Comment by 0crypto0** [comment]
no errors on console.
the audio element plays on its on.
the state is suspended, i call resume but it seems the onstatechange event is not fired

**Comment by chrisguttandin** [comment]
Do you call `resume()` from within a click handler? Can you share that part of your code?

**Comment by 0crypto0** [comment]
i use this function 

  unlockAudioContext = (audioCtx) => {
    if (audioCtx.state !== 'suspended') return;
    const b = document.body;
    const events = ['touchstart', 'touchend', 'mousedown', 'keydown'];
    events.forEach(e => b.addEventListener(e, unlock, false));
    function unlock() { audioCtx.resume().then(clean); }
    function clean() { events.forEach(e => b.removeEventListener(e, unlock)); }
  }
now my state keeps getting interrupted.

**Comment by chrisguttandin** [comment]
Just to clarify. Is that a different error now?

Is it similar to the issue described here: Tonejs/Tone.js#716?

**Comment by 0crypto0** [comment]
yes it's a different  error now.
but it's not caused by the same actions described in the tone.js

**Comment by chrisguttandin** [comment]
Okay, this "interrupted" state seems to be something new. Would you be able to provide a little example that reproduces the error. Maybe using CodePen or StackBlitz. I'm very much interested in fixing this (if possible) but doing so without a reproducible example is close to impossible.

**Comment by chrisguttandin** [comment]
Hi @0crypto0, does the workaround that I proposed [here](https://github.com/Tonejs/Tone.js/pull/716#issuecomment-686066170) work for you as well?

In your case it would be something like this:

```js
const osc = this.audioContext.createOscillator();
const gain = this.audioContext.createGain();

gain.gain.value = 1e-37;
osc.connect(gain).connect(this.audioContext.destination);
osc.start();
```

**Comment by chrisguttandin** [comment]
I added the fix mentioned above and published the changes as v25. Please let me know if the state still happens to be 'interrupted' when using the new version.

**Comment by 0crypto0** [comment]
Thanks, i will test it soon and let you know.
