### ISSUE TITLE
isSupported return false in v84 Chrome and v86 Chromium

### ISSUE THREAD

**Issue by Francis-Tao-jinjin** [chrisguttandin/standardized-audio-context#955]
It is related to tonejs, I foke the latest tonejs and trying to make it support old safari. At the place it import components from  
 standardized-audio-context, I add a few lines of code to call isSupported to see the result. to my surprised, it show 'false' on the latest Chrome and Chromium. I already using v24.1.26. Is there anything wrong with isSupported test?

<img width="308" alt="Screen Shot 2020-08-26 at 6 29 00 PM" src="https://user-images.githubusercontent.com/17539265/91293088-103c0380-e7ca-11ea-97ef-6effa288ba0c.png">
<img width="616" alt="Screen Shot 2020-08-26 at 6 28 50 PM" src="https://user-images.githubusercontent.com/17539265/91293094-129e5d80-e7ca-11ea-93e0-4ddd1572e015.png">

**Comment by chrisguttandin** [comment]
Hi @Francis-Tao-jinjin, thanks a lot for reporting this. I added a test now to make sure `isSupported()` actually resolves to true in supported browsers. Previously I only tested that it resolves to false in unsupported browsers.

The fix should be released with the next version which is supposed to be v25.

**Comment by chrisguttandin** [comment]
I just published v25 to npm. Please let me know if the problem still persists.
