### ISSUE TITLE
MacOS Safari `NotSupportedError`

### ISSUE THREAD

**Issue by cah-dunn** [chrisguttandin/standardized-audio-context#956]
I'm encountering an issue that only occurs on MacOS Safari (both v13 and v14). It is working fine in Safari on iOS/iPadOS.

I am on the latest package version (v25.0.3).

`new AudioContext()` errors out with a `NotSupportedError`
![image](https://user-images.githubusercontent.com/34485176/93623347-38231f00-f9a4-11ea-99e5-c5758a769585.png)

Let me know if I can provide any additional details.

**Comment by chrisguttandin** [comment]
Hi Kyle, can you please tell me a little more about the environment? Which macOS version is it? Does it have a sound card? Does `new webkitAudioContext()` work?

I just tested https://chrisguttandin.github.io/standardized-audio-context-demo/ on macOS Mojave with Safari v14 and it worked as expected.

**Comment by cah-dunn** [comment]
@chrisguttandin Wow, this is pretty bizarre. I only get this error if I am using my microphone. I am using a bluetooth Jabra headset,  it may have to do the with codec changing to SCO (mic) from SBC (no mic)? If I pull a system report and go to Hardware > Audio > Jabra I can see the output sample rate switch from 16000 to 48000 when my microphone is enabled.

It does work if I'm using the native `webkitAudioContext` however.

I'm on macOS Catalina (10.15.5), 2019 MacBook Pro 16"

**Comment by cah-dunn** [comment]
Ah, I imagine the fact that it's going down to 16000 is precisely the problem after seeing your note here: https://github.com/chrisguttandin/standardized-audio-context#createbuffer--audiobuffer

**Comment by chrisguttandin** [comment]
Hi @cah-dunn, thanks for providing further details. I think you're suspicion is correct. There is at least one wrapper that immediately creates an AudioBuffer.

https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/wrap-audio-buffer-source-node-stop-method-nullified-buffer.ts#L7

Could you try modifying the source? I wonder what happens if you replace ...

```
const nullifiedBuffer = nativeContext.createBuffer(1, 1, nativeContext.sampleRate); 
```
... with ...
```
const nullifiedBuffer = nativeContext.createBuffer(1, 1, 44100);
```
. Maybe that's all it takes to fix the problem.

**Comment by cah-dunn** [comment]
Hey @chrisguttandin, thanks for the quick responses. If I change the line you linked as well as this one (https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/native-constant-source-node-faker-factory.ts#L16) I no longer experience the issue. Easy fix ✅. Would you like me to submit a PR?

**Comment by chrisguttandin** [comment]
Yes, that would be very welcome. Many thanks in advance.
