### ISSUE TITLE
'panWaveShaperNode' undefined in iOS 14

### ISSUE THREAD

**Issue by justin-cotarla** [chrisguttandin/standardized-audio-context#959]
While using [Tone.js](https://github.com/Tonejs/Tone.js), I've encountered a bug that started occuring right after updating to iOS 14.

An error occurs in `native-stereo-panner-node-faker-factory.ts` at line 163, where evaluating `panWaveShaperNode.inputs`  fails because `panWaveShaperNode` is undefined.

The full stack trace:
```
Unhandled Rejection (TypeError): undefined is not an object (evaluating 'panWaveShaperNode.inputs[0]')

connectGraph
node_modules/standardized-audio-context/build/es2019/factories/native-stereo-panner-node-faker-factory.js:109

whenConnected
node_modules/standardized-audio-context/build/es2019/factories/native-stereo-panner-node-faker-factory.js:240

(anonymous function)
node_modules/standardized-audio-context/build/es2019/factories/monitor-connections.js:13

(anonymous function)
node_modules/standardized-audio-context/build/es2019/helpers/wrap-audio-node-disconnect-method.js:7
connectNativeAudioNodeToNativeAudioNode
node_modules/standardized-audio-context/build/es2019/helpers/connect-native-audio-node-to-native-audio-node.js:8

connect
node_modules/standardized-audio-context/build/es2019/factories/audio-node-constructor.js:323
```

For reference, the calling code in Tone.js is at line 111 of [CrossFade.ts](https://github.com/Tonejs/Tone.js/blob/dev/Tone/component/channel/CrossFade.ts).

I'm inclined to think this might be caused by I change in webviews in iOS14, which I believe would break this library, and not Tone.js. Forgive if this is not the case.

**Comment by chrisguttandin** [comment]
Hi @justin-cotarla, this looks like Tonejs/Tone.js#720. If that's the case it should be fixed in standardized-audio-context and be fixed for Tone.js with the next update.

I'm closing this now but please feel free to reopen it if the error still gets thrown with the newest version of standardized-audio-context.
