### ISSUE TITLE
Chrome on Android AudioWorklets are glitchy

### ISSUE THREAD

**Issue by ichabodcole** [chrisguttandin/standardized-audio-context#960]
@chrisguttandin Just thought I would let you know there is currently a bug in Chrome for Android when using AudioWorklets, which creates hellish glitching in both the worklet and other non worklet nodes. I was thinking maybe this would be a case where it would be better to default to the ScriptProcessorNode under the hood, at least until a fix is released. 

I created a stackblitz demo to illustrate the issue.
https://stackblitz.com/edit/js-mobile-chrome-audioworket-bug-demo-standardized?file=index.js

There is currently a bug report for this as well.
https://bugs.chromium.org/p/chromium/issues/detail?id=1090441&q=audioworklet%20chrome%20android&can=2

**Comment by chrisguttandin** [comment]
Wow, that's a pretty annoying bug. Thanks for bringing this to my attention. However I'm not sure what to do with it. Given that regular AudioNodes cause dropouts as well I wonder if it will make any difference to use a ScriptProcessorNode instead of an AudioWorklet.

**Comment by ichabodcole** [comment]
Oh, I should clarify, this bug only relates to the AudioWorkletNode, it's just that as soon as you load and instantiate the AudioWorkletNode it happens to make everything else already running super glitchy as well. I can also confirm this does not happen when using the ScriptProcessorNode, which I recently switch away from to get better performance (ironically...). That said, totally understand if you don't want to sniff around for specific browser versions to "fix" this sort of issue.

**Comment by chrisguttandin** [comment]
Okay, I see. Thanks for clarifying that.

Normally I try to do functional checks whenever possible instead of doing ua sniffing. But in that case there seems to be no other option. The problem is that as a user of standardized-audio-context you don't really have the choice to deliberately use the ScriptProcessorNode since it is not part of the API surface anymore.

**Comment by ichabodcole** [comment]
No problem! Agree, this is sort of an unfortunately tough case with no ideal solution :(. In any case I will keep an eye on that bug tracker. It's currently a priority 1 fix, which is good, but no idea how long it will actually take to get fixed and deployed (there are a lot of priority ones on the current list).

**Comment by chrisguttandin** [comment]
Hi @ichabodcole, the Chromium issue for this bug was marked as fixed. Do you think we can close this now, too?

**Comment by ichabodcole** [comment]
@chrisguttandin YES, fixed on deployed, thank Zeus! What a saga it was to follow that bug though haha.
