### ISSUE TITLE
ConvolverNode cuts off before tail-time is completed

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#961]
[Here's a demo](https://codesandbox.io/s/nervous-darkness-m2558?file=/src/index.ts) of making a simple ConvolverNode reverb and playing a short OscillatorNode blip through it. 

If you play the example without standardized-audio-context, the entire tail-time of the convolver will play through. but when using std-audio-context, the audio gets cut short before the reverb fully decays. 

related to Tonejs/Tone.js#746

**Comment by chrisguttandin** [comment]
Hi @tambien, thanks for making me aware of this. I updated the code to add proper tail-time handling (at least for the ConvolverNode). I also updated your demo: https://codesandbox.io/s/convolver-node-too-short-forked-nc5ir

I just published v25.1 which contains the fix.

**Comment by tambien** [comment]
thank you for taking care of this so quickly!
