### ISSUE TITLE
Scoping issue when using SAC across libraries

### ISSUE THREAD

**Issue by ichabodcole** [chrisguttandin/standardized-audio-context#963]
Hi @chrisguttandin ran into an unforeseen scoping issue when trying to use SAC across multiple libraries. 
The setup I have is as follows. 

1. Library A uses SAC, creating various audio nodes and using some of the helper guards (e.g. isAnyAudioNode).
2. Library B also uses SAC and library A, and creates various audio nodes and uses helpers.
3. Library B creates the new AudioContext using SAC and passes this instance to various classes imported from library A, which expect an instance of SAC's AudioContext. Additionally, Audio nodes created in Lib A may connect to nodes created in Lib B and vice versa.

The issue I ran into was that in library A I am using an "isAnyAudioNode" guard from SAC, however this would fail for any new nodes passed to library A which were created in library B via importing from SAC. I was able to figure out this was due to the AUDO_NODE_STORE having two instances in the compiled code, one created in the context of library A, then another in library B. When I pass a node created in SAC from library B to library A, library A's AUDIO_NODE_STORE does not contain that node and returns false.

Ultimately, I was able to get around this issue by exporting the SAC AudioContext from library A, and then importing and using that in library B when instantiating the audio context and creating additional nodes. This however means that I cannot just import SAC into library B directly, but instead have to export functionality I would like to use from SAC out of library A and then into library B to avoid the scoping issue. Just to be clear I never actually instantiate an AudioContext in library A, I am instantiating the AudioContext in library B and then passing it to library A.

Let me know if that is that is all clear as mud :D.

Not sure if there is any reasonable way to rectify this in the library or my build, but probably good to be aware of (if not already). Also, if you have have any insight in to getting around this in a better way, would love to know. Thanks!

**Comment by chrisguttandin** [comment]
Hi Cole,

what bundler are you using? Normally there should be some deduplication going on which makes sure there is only one instance of standardized-audio-context in the build.

Can you try running `npm ls standardized-audio-context` to see how many versions of standardized-audio-context you have?

**Comment by ichabodcole** [comment]
Hey @chrisguttandin 
FYI, I'm using rollup. I dug into this a bit more based on your comment, and was able to solve the issue by listing SAC as a `peerDependency` instead of a `dependency` in "Lib A", and marking it as `external` in "LibA"s rollup build config so that it is not included in the bundle. Not sure if there is any more automagical way to handle that (still getting comfortable with rollup), but working as desired now. Thanks, feel free to close the issue!

**Comment by chrisguttandin** [comment]
There is of course no "npm police" which makes sure each packages is published in the same way. :-) But I think a general rule of them thumb is to not pre-bundle the dependencies.

In case it helps here is the rollup config of standardized-audio-context: https://github.com/chrisguttandin/standardized-audio-context/blob/master/config/rollup/bundle.js. I use rollup to produce the es5 bundle but I [exclude any dependency](https://github.com/chrisguttandin/standardized-audio-context/blob/master/config/rollup/bundle.js#L13). This has the downside that every consumer of this library needs to use a bundler as well. But it allows that bundler to do deduplication.

I'll close this now. I'm glad you found a solution. Feel free to reopen this if you think there is anything that could be done to make this process easier.

**Comment by ichabodcole** [comment]
Chris, thanks for the additional information, that is very helpful as I was struggling to set up my library to support es and umd formats in a practical way, so enforcing the requirement of a bundler makes a lot of sense.
