### ISSUE TITLE
AudioWorklet is undefined

### ISSUE THREAD

**Issue by cactrot** [chrisguttandin/standardized-audio-context#976]
I am developing an app on Quasar.
I ran isSupported on both platforms I'm using and it returned "true" on both.
Oscillators work well on both but the worklet only works on one.
I tried with a capitol 'A' and lowercase.
Thanks in advance.

On windows 10 (Chrome 90.0.4430.72)(Quasar 1.14.7)(standardized-audio-context 25.1.15) :
Works fine.

On iPad Pro ( iOS 14.4 )(xcode12.4)((Quasar 1.14.7)standardized-audio-context 25.1.15) simulator : 
[Promise/async]: "TypeError: undefined is not an object (evaluating 'audioWorklet.addModule')"

    import { AudioContext, AudioWorkletNode } from 'standardized-audio-context'
    
    // create web audio api context
    // var AudioContext = window.AudioContext || window.webkitAudioContext
    var audioCtx = new AudioContext()

    const blobCode = () => {
      return `
    class WhiteNoiseProcessor extends AudioWorkletProcessor {
      process (inputs, outputs, parameters) {
        const output = outputs[0]
        output.forEach(channel => {
          for (let i = 0; i < channel.length; i++) {
            channel[i] = Math.random() * 2 - 1
          }
        })
        return true
      }
    }

    registerProcessor('white-noise-processor', WhiteNoiseProcessor)`
    }

    const blob = new Blob([blobCode()], { type: 'application/javascript; charset=utf-8' })

    const workletUrl = window.URL.createObjectURL(blob)

    const audioWorklet = audioCtx.audioWorklet
    await audioWorklet.addModule(workletUrl) //error audioWorklet undefined
    const noiseSrc = new AudioWorkletNode(audioCtx, `'white-noise-processor')`

**Comment by cactrot** [comment]
isSecureContext came back as 'false'

**Comment by chrisguttandin** [comment]
I'm not familiar with the xCode simulator. Do you know if it is possible to make it run a secure context?

**Comment by cactrot** [comment]
It appears you found the problem.
The dev server for capacitor serves the contents over http.
I tried switching the build mode from dev to release so everything was embedded in the app.
isSecureContext evaluates as true and the worklet works.

**Comment by chrisguttandin** [comment]
Thanks for reporting back. I'm going to close the issue.
