### ISSUE TITLE
Error when using with SoundfontPlayer and Angular 11.2

### ISSUE THREAD

**Issue by conde2** [chrisguttandin/standardized-audio-context#978]
Running in Angular 11.2

![image](https://user-images.githubusercontent.com/2137569/119064061-e3abc580-b9b0-11eb-8dcf-fe6a31e0e8d6.png)

Using standardized-audio-context with SoundfontPlayer throws me this error.
https://github.com/danigb/soundfont-player

UPDATE 1: Update the image with a better traceback.

**Comment by chrisguttandin** [comment]
Hi @conde2, can you please provide some sample code which causes the issue? Without being able to reproduce it I have no idea what is causing the issue. Also standardized-audio-context is not mentioned in the stack trace at all. Are you sure the issue is caused by standardized-audio-context?

**Comment by conde2** [comment]
I manage to get a better traceback, I can upload a minimum reproduction repository if you wish.


![image](https://user-images.githubusercontent.com/2137569/119059833-78112a80-b9a7-11eb-8ebe-b83c633d2b62.png)

**Comment by chrisguttandin** [comment]
Thanks a lot for the detailed report and for the repo to reproduce the error. That made it very easy for me to track down the problem.

Although I do not really understand why my changes make any difference the error seems to be catched correctly now. As a side effect the code is also a bit more elegant now. :-)

Thanks again for reporting this.

**Comment by chrisguttandin** [comment]
v25.2.3 contains the fix.

**Comment by conde2** [comment]
Thanks! The changes fixed the error.

Maybe the error was something related how Typescript transpile the code to javascript... Well problem solved anyway =)
