### ISSUE TITLE
Unable to reposition listener in Firefox

### ISSUE THREAD

**Issue by lizadaily** [chrisguttandin/standardized-audio-context#985]
Thank you for the great package!

What is the correct way to set `listener.positionX` and `listener.positionY` with this package? Changing the value fields works on Chrome, but Firefox along with several other browsers does not make these values available yet (https://developer.mozilla.org/en-US/docs/Web/API/AudioListener), so I feel forced to use the deprecated `setPosition()`. However, this does not seem to be available on this package's `IAudioListener` implementation. Is this completely unsupported, or is there a way to retain compatible cross-browser behavior?

**Comment by lizadaily** [comment]
Actually, I see now that I can cast `IAudioContext.listener` to the native `AudioListener` and get access to the deprecated method that way. Is this the recommended approach?

**Comment by chrisguttandin** [comment]
Hi @lizadaily, it should work in Firefox as it does in Chrome or any other browser.

```javascript
import { AudioContext } from 'standardized-audio-context';

const audioContext = new AudioContext();

audioContext.listener.positionX.setValueAtTime(1, audioContext.currentTime);
```

Internally a `ScriptProcessorNode` gets used to call `setPosition()` almost in time. But of course only if necessary.

Does that answer your question?

**Comment by lizadaily** [comment]
Thanks, @chrisguttandin - this makes sense! I realized that even setting the value directly works. My inconsistent behavior was related to a timing issue where the audio context and listener were initialized _after_ the initial position value was modified. This did not throw an obvious error in Chrome, but did in Firefox. Thank you!
