### ISSUE TITLE
iOS 15.2 Support

### ISSUE THREAD

**Issue by wbuchwalter** [chrisguttandin/standardized-audio-context#991]
Hello,

I cannot seem to get the Audio API to work on iOS 15 (my exact version at the moment is 15.2.1). 
I Tried https://chrisguttandin.github.io/standardized-audio-context-demo/ with Safari/Firefox/Edge/Chrome but I am unable to get any sound.

Wondering is seeing the same thing?

Thanks!

**Comment by wbuchwalter** [comment]
So this was actually caused by the physical mute switch on the iPhone.
The physical switch prevents Web Audio API from playing any sound, but not the `<audio>` tags for some reason.

See https://www.npmjs.com/package/unmute-ios-audio for a fix.

**Comment by chrisguttandin** [comment]
Hi @wbuchwalter, thanks for reporting the fix.
