### ISSUE TITLE
`AudioWorkletNode` TypeError: The superclass is not a constructor.

### ISSUE THREAD

**Issue by maximedupre** [chrisguttandin/standardized-audio-context#998]
This might be a bad bug ticket, because I'm not sure it's easily reproducible, so feel free to close it right away. I'm simply taking a chance in case you have a solution 😁

On Safari iOS 16.2 → `export class WAMController extends AudioWorkletNode` causes this error message:

> Error: Uncaught (in promise): TypeError: The superclass is not a constructor.

When I log `AudioWorkletNode` I get undefined.

```
import { AudioWorkletNode } from 'standardized-audio-context';

console.log(AudioWorkletNode); // undefined
```

When I log the whole module, funny enough, only the `AudioWorkletNode` is missing 😅🤷🏻‍♂️

![image](https://user-images.githubusercontent.com/5158181/213803619-bcfebf2a-cfbe-42ee-b365-c2b8fe7c0c08.png)

I'm not sure if this has something to do with the Angular build chain, or the fact that I'm using Tone.js (uses `standardized-audio-context` as a dep)

Anyway, thanks for reading 😁

**Edit** 

`addAudioWorkletModule` is also missing 🤔

**Comment by maximedupre** [comment]
Found the issue - `AudioWorklet` only works in a secure context 🥲 So when using localhost, you need to serve your app via HTTPS (self-signed certificates).

**Comment by chrisguttandin** [comment]
Yes, I was just going to reply exactly that. :-) But normally localhost is considered to be a secure context.
